/**
 * Session Planning Model loader — RC1.
 *
 * Canonical source: the workbook committed verbatim at
 * `back/data/session-planning/session-planning-model.rc1.xlsx`, projected completely into
 * `session-planning-model.rc1.json` (generated by `project-workbook.py` — never hand-edit).
 *
 * WHAT THIS OWNS, AND WHAT IT MUST NOT. Christian's Governance Standard is explicit: the Session
 * Planning Model models COACHING DECISIONS, not sport knowledge. It owns Learning Goals, Practice
 * Situations, coach-facing definitions and entry language. It does NOT own Game Problems,
 * affordances, environmental manipulations or representative design — those stay with the sport
 * knowledge layer. So this module deliberately exposes registry data and nothing else: no scoring,
 * no candidate pools, no sport mappings recreated in code. The Engine Translation sheet
 * is a REFERENCE to be passed through, never a place to invent a mapping.
 *
 * WHY THE GATE CHECKS REFERENCES RATHER THAN COUNTS. Every other workbook we ingest carries a
 * Metadata sheet declaring expected row counts, which is what lets a loader detect truncation — and
 * after our EM review Christian made Version Metadata a required element of future Knowledge
 * Schemas. This workbook has no Metadata sheet, so there is nothing to compare against. Rather than
 * writing expected counts HERE (which would just relocate the authority into code and defeat the
 * whole pattern), the gate enforces referential integrity: every Practice Situation must belong to a
 * real Learning Goal, every Entry Language phrase must point at one, and every Learning Goal must
 * have an Engine Translation row. That is a stronger guarantee than a row count, because it fails on
 * a broken relationship rather than merely a missing line.
 *
 * ENGINE TRANSLATION IS UNPOPULATED AT RC1. All eleven rows read TBD. That is a known, expected
 * state — not damage — so it is REPORTED rather than treated as a load failure. `translationStatus()`
 * makes it countable, because the difference between "not populated yet" and "populated wrongly"
 * has to stay visible while it is being filled in.
 */
import workbook from './session-planning-model.rc1.json'

export type PlanningRow = Record<string, string | number | null>

interface SessionPlanningWorkbook {
    source_workbook: string
    header_row: number
    learning_goals: PlanningRow[]
    practice_situations: PlanningRow[]
    entry_language: PlanningRow[]
    engine_translation: PlanningRow[]
    governance: PlanningRow[]
}

const WB = workbook as unknown as SessionPlanningWorkbook

/** The workbook's own column names, kept in one place so a rename is a one-line fix. */
const COL = {
    goalId: 'ID',
    goalPhase: 'Phase',
    goalOrder: 'Display Order',
    goalName: 'Learning Goal',
    goalDefinition: 'Coach Definition',
    goalChooseWhen: 'Choose This When...',
    goalStatus: 'Status',
    situationId: 'ID',
    situationParent: 'Parent ID',
    situationOrder: 'Display Order',
    situationName: 'Practice Situation',
    phrase: 'Coach Phrase',
    phraseGoalId: 'Learning Goal ID',
    translationGoalId: 'Learning Goal ID',
    translationPrimary: 'Primary GP IDs',
    translationSecondary: 'Secondary GP IDs',
} as const

const text = (row: PlanningRow, column: string): string => {
    const value = row[column]
    return value === null || value === undefined ? '' : String(value).trim()
}

/** The placeholder Christian used for unpopulated Game Problem references. */
const UNPOPULATED = 'TBD'

export interface PlanningIntegrityResult {
    valid: boolean
    errors: string[]
}

/**
 * Load-time integrity gate — referential, for the reason in the header note.
 *
 * Each check corresponds to a way the coach conversation breaks WITHOUT erroring: a Practice
 * Situation orphaned from its goal never appears, a phrase pointing at a deleted goal routes
 * nowhere, and a Learning Goal with no Engine Translation row is a dead end the coach only discovers
 * after answering every question.
 */
export function validateSessionPlanningModel(data: SessionPlanningWorkbook = WB): PlanningIntegrityResult {
    const errors: string[] = []

    const goalIds = new Set<string>()
    for (const goal of data.learning_goals) {
        const id = text(goal, COL.goalId)
        if (!id) {
            errors.push(`A Learning Goal row has no ID (${text(goal, COL.goalName) || 'unnamed'}).`)
            continue
        }
        if (goalIds.has(id)) errors.push(`Duplicate Learning Goal ID "${id}".`)
        goalIds.add(id)

        // The coach-facing fields. A goal with no name or definition renders as a blank choice.
        for (const column of [COL.goalName, COL.goalDefinition, COL.goalPhase]) {
            if (!text(goal, column)) errors.push(`Learning Goal "${id}" has no ${column}.`)
        }
    }

    const situationIds = new Set<string>()
    for (const situation of data.practice_situations) {
        const id = text(situation, COL.situationId)
        if (!id) {
            errors.push('A Practice Situation row has no ID.')
            continue
        }
        if (situationIds.has(id)) errors.push(`Duplicate Practice Situation ID "${id}".`)
        situationIds.add(id)

        const parent = text(situation, COL.situationParent)
        if (!goalIds.has(parent)) {
            errors.push(
                `Practice Situation "${id}" has Parent ID "${parent}", which is not a Learning Goal. ` +
                    `An orphaned situation is never offered to a coach — it does not error, it just disappears.`
            )
        }
    }

    for (const entry of data.entry_language) {
        const phrase = text(entry, COL.phrase)
        const goalId = text(entry, COL.phraseGoalId)
        if (!phrase) errors.push('An Entry Language row has no coach phrase.')
        if (!goalIds.has(goalId)) {
            errors.push(`Entry Language "${phrase}" points at Learning Goal "${goalId}", which does not exist.`)
        }
    }

    const translated = new Set(data.engine_translation.map((r) => text(r, COL.translationGoalId)))
    for (const id of goalIds) {
        if (!translated.has(id)) {
            errors.push(
                `Learning Goal "${id}" has no Engine Translation row. A coach could select it and reach nothing.`
            )
        }
    }

    return { valid: errors.length === 0, errors }
}

export interface TranslationStatus {
    total: number
    populated: number
    unpopulated: string[]
}

/**
 * How much of the coach-intent-to-knowledge bridge actually exists. Reported rather than asserted, because at
 * RC1 the honest answer is "none of it" and that is a legitimate state to load in — but one nobody
 * should be able to forget while building against it.
 */
export function translationStatus(data: SessionPlanningWorkbook = WB): TranslationStatus {
    const unpopulated: string[] = []
    for (const row of data.engine_translation) {
        const primary = text(row, COL.translationPrimary)
        if (primary === '' || primary.toUpperCase() === UNPOPULATED) {
            unpopulated.push(text(row, COL.translationGoalId))
        }
    }
    return {
        total: data.engine_translation.length,
        populated: data.engine_translation.length - unpopulated.length,
        unpopulated,
    }
}

/** Game Problem references for a Learning Goal, or `null` while the bridge is unpopulated. */
export function gameProblemsForLearningGoal(
    learningGoalId: string,
    data: SessionPlanningWorkbook = WB
): { primary: string[]; secondary: string[] } | null {
    const row = data.engine_translation.find((r) => text(r, COL.translationGoalId) === learningGoalId)
    if (!row) return null

    const ids = (column: string): string[] => {
        const raw = text(row, column)
        if (raw === '' || raw.toUpperCase() === UNPOPULATED) return []
        return raw
            .split(/[;,]/)
            .map((v) => v.trim())
            .filter(Boolean)
    }

    const primary = ids(COL.translationPrimary)
    // No primary reference means the coach-to-knowledge bridge is not built for this goal. Returning null rather than
    // an empty array keeps callers from treating "unpopulated" as "no game problems apply", which
    // are opposite meanings — and the Implementation Guide requires failing loudly on a missing
    // reference rather than substituting a default.
    return primary.length === 0 ? null : { primary, secondary: ids(COL.translationSecondary) }
}

const byOrder = (a: PlanningRow, b: PlanningRow, column: string) => Number(a[column] ?? 0) - Number(b[column] ?? 0)

export const sessionPlanningModel = {
    sourceWorkbook: WB.source_workbook,
    /** Learning Goals in the workbook's declared display order — the order is a coaching decision. */
    learningGoals: () => [...WB.learning_goals].sort((a, b) => byOrder(a, b, COL.goalOrder)),
    /** Phases in first-appearance order, which is how the registry is authored. */
    phases: (): string[] => {
        const seen: string[] = []
        for (const goal of WB.learning_goals) {
            const phase = text(goal, COL.goalPhase)
            if (phase && !seen.includes(phase)) seen.push(phase)
        }
        return seen
    },
    learningGoalsForPhase: (phase: string) =>
        WB.learning_goals.filter((g) => text(g, COL.goalPhase) === phase).sort((a, b) => byOrder(a, b, COL.goalOrder)),
    learningGoal: (id: string) => WB.learning_goals.find((g) => text(g, COL.goalId) === id),
    /**
     * Practice Situations for a goal, in display order. An EMPTY result is meaningful and expected:
     * the Implementation Guide says a goal with no situations must continue automatically rather
     * than showing an empty step.
     */
    practiceSituationsFor: (learningGoalId: string) =>
        WB.practice_situations
            .filter((s) => text(s, COL.situationParent) === learningGoalId)
            .sort((a, b) => byOrder(a, b, COL.situationOrder)),
    entryLanguage: () => WB.entry_language,
    /**
     * Entry-language lookup. Deliberately a HINT, not a router — the Implementation Guide is explicit
     * that entry language must never override an explicit coach selection.
     */
    learningGoalIdForPhrase: (phrase: string): string | null => {
        const needle = phrase.trim().toLowerCase()
        const hit = WB.entry_language.find((e) => text(e, COL.phrase).toLowerCase() === needle)
        return hit ? text(hit, COL.phraseGoalId) : null
    },
    governanceRules: (): string[] => WB.governance.map((r) => text(r, 'Rule')).filter(Boolean),
}
