/**
 * Freeze the A04 concrete game as the canonical rendering fixture — by RUNNING the closure, not by
 * transcribing it.
 *
 * The first version of this fixture was hand-built from the closure run's printed output, and that is a
 * fork waiting to happen: the moment the engine changes, a hand-copied fixture keeps testing the old
 * game while claiming to be the current one. The project has already been bitten by a harness that
 * reproduced a pipeline *approximately*. So this runs the same stages as `run-first-game.ts`, in the same
 * order, and refuses to write anything unless the run is actually render-eligible.
 *
 * **It is also the single definition of what the Golden Case IS.** `buildGoldenCase` below is exported and
 * used by `fixture-currency.unit.ts` to recompute the game and compare digests. That is deliberate: a guard
 * with its OWN replica of these stages would be a second harness, free to drift from the one that writes
 * the artifact — the exact failure this file's own header warns about. One builder, two callers.
 *
 * Run: npm run freeze:a04
 */
import fs from 'node:fs'
import path from 'node:path'

import { isStampedHalt } from '../derivation/emit'
import { canonical, digest, runDerivation, runStages0to10 } from '../derivation/engine'
import { indexRegister } from '../derivation/register'
import { assembleResolvedGame } from '../derivation/resolved-game'
import { derivationInputFor, selectFor } from '../derivation/run-bounded-selection'
import { completeConcreteGame } from '../realization/assemble-concrete-game'
import { runPostRealizationGates } from '../realization/post-realization-gate'
import { checkRealization, isRefused, realize, Realized } from '../realization/realize'

export const CHOICES = path.resolve(__dirname, '../../../../docs/audits/a04-realization-choices.json')
export const OUT = path.resolve(__dirname, '../../../../docs/audits/a04-concrete-game-fixture.json')

/**
 * **His instruction, recorded in the artifact it governs, and it stays there.** The first generated version
 * of the fixture replaced it with a description of the generator, which deleted the owner's words from the
 * artifact they govern — the project's oldest failure mode, committed against a ruling.
 */
const NOTE =
    'THE CANONICAL A04 RENDERING FIXTURE. Christian: "use the exact A04 concrete game from this closure ' +
    'run as the canonical rendering fixture. For this first test, do not reselect or re-realize it." So ' +
    'rendering reads THIS artifact and never a fresh run. Regenerated by `npm run freeze:a04` only when ' +
    'the chain itself is corrected — as on 1 October 2026, when the derived roster was found never to ' +
    'reach the concrete game — and never hand-edited. If a run would otherwise produce a different game, ' +
    'that is a separate finding and this file does not move. Since 7 October that finding is not left to ' +
    'be noticed: `fixture-currency.unit.ts` recomputes the game every run and fails on undeclared drift.'

/** Raised where the Golden Case cannot be produced at all, so a currency verdict is impossible rather than false. */
export class GoldenCaseUnavailable extends Error {}

/**
 * The Golden Case body — everything the fixture holds except the owner's note.
 *
 * **The realization choices are part of it, on his ruling of 7 October** (*"Include the realization choices
 * in the guarded Golden Case as proposed"*). They are not an input the guard happens to read: which values
 * realization chose is part of what makes this game the Golden Case rather than a neighbouring one, so a
 * change to `a04-realization-choices.json` moves the digest and must be declared like any other.
 */
export function buildGoldenCase(): Record<string, unknown> {
    const input = derivationInputFor(selectFor('A04', null))
    const result = runDerivation(input)
    if (isStampedHalt(result)) throw new GoldenCaseUnavailable('the derivation halted, so there is no game to freeze or compare')

    const staged: any = runStages0to10(input)
    const index = indexRegister(input.register)
    const resolved = assembleResolvedGame(result, staged.classes, index, input.contracts)
    if (!resolved.coherence.realizationAuthorized) {
        throw new GoldenCaseUnavailable(
            `A04 is not realization-authorized: ${resolved.coherence.notAuthorizedBecause.join('; ') || 'no reason stated'}`,
        )
    }

    const supplied = JSON.parse(fs.readFileSync(CHOICES, 'utf8'))
    const realizationResult = realize(resolved, supplied.choices, supplied.instantiations, index, input.envelope)
    if (isRefused(realizationResult)) throw new GoldenCaseUnavailable(`realization refused: ${realizationResult.because.join('; ')}`)
    const realized = realizationResult as Realized

    // Same order as the closure run: entail over the concrete game, THEN check it, THEN gate it.
    const gateContext = { ...staged.gateContext, contracts: input.contracts }
    const entailed = completeConcreteGame(gateContext, realized)

    const checks = checkRealization(resolved, realized)
    const accepted = !checks.nothingClosedWithoutAuthority.length && !checks.nothingLost.length && !checks.nothingInvented.length
    const post = runPostRealizationGates(
        gateContext,
        resolved.coherence.postRealizationRequired.map(o => ({ checkId: o.checkId, clause: o.clause })),
        realized,
    )

    // **Refuse to produce anything that is not the closed game.** A fixture that captured a failing run would
    // quietly become the thing rendering is tested against.
    if (!accepted) throw new GoldenCaseUnavailable(`realization acceptance FAILED: ${JSON.stringify(checks)}`)
    if (!post.validated) throw new GoldenCaseUnavailable(`post-realization Gate A NOT PASSED: ${post.outstanding.join('; ')}`)

    return {
        provenance: resolved.provenance,
        closure: {
            preRealization: resolved.coherence.preRealization,
            realizationAuthorized: resolved.coherence.realizationAuthorized,
            postRealizationValidated: post.validated,
            renderEligible: accepted && post.validated,
        },
        envelope: {
            players: (input.envelope as any).players,
            lengthM: (input.envelope as any).area?.length_m ?? (input.envelope as any).lengthM,
            widthM: (input.envelope as any).area?.width_m ?? (input.envelope as any).widthM,
            durationMin: (input.envelope as any).duration_min ?? (input.envelope as any).durationMin,
            roles: (input.envelope as any).roles ?? {},
        },
        game: realized.game,
        record: realized.record,
        status: {
            derived: resolved.derived.map(d => ({ path: d.path, lineId: d.lineId, value: d.value })),
            choices: realized.record.choices.map(c => ({ path: c.path, lineId: c.lineId, value: c.value })),
            instantiations: realized.record.instantiations.map(i => ({ path: i.path, classId: i.classId, handle: i.handle, memberIndex: i.memberIndex, member: i.member })),
            entailed,
            geometry: realized.record.geometry,
            jointConditions: resolved.jointConditions,
            notEstablished: resolved.notEstablished.map(n => ({ path: n.path, lineId: n.lineId, reason: n.reason, declared: n.declared })),
        },
    }
}

/**
 * One digest over the Golden Case body, taken the same way for a live rebuild and for the frozen file.
 *
 * **The owner's `note` is excluded and nothing else is.** Editing his wording must not read as drift, and
 * every other field is part of the game or of the closure verdict that admitted it.
 *
 * It uses the engine's own `canonical` and `digest` rather than a new hashing scheme: `canonical` sorts keys
 * recursively so a JSON round trip cannot move the number, and leaves ARRAY order alone, which is right —
 * instantiation order fixes which handle each member gets, so two orderings are two different games.
 */
export function goldenCaseDigest(body: Record<string, unknown>): string {
    const { note, ...rest } = body as Record<string, unknown> & { note?: unknown }
    return digest(canonical(rest))
}

if (require.main === module) {
    const body = buildGoldenCase()
    fs.writeFileSync(OUT, `${JSON.stringify({ note: NOTE, ...body }, null, 1)}\n`, 'utf8')
    const status = body.status as any
    console.log(`froze ${path.basename(OUT)}`)
    console.log(`  render-eligible   ${(body.closure as any).renderEligible ? 'YES' : 'NO'}`)
    console.log(`  input digest      ${(body.provenance as any).inputDigest}`)
    console.log(`  GOLDEN CASE       ${goldenCaseDigest(body)}`)
    console.log(
        `  derived ${status.derived.length} · choices ${status.choices.length} · instantiations ${status.instantiations.length} · entailed ${status.entailed.length} · geometry ${status.geometry.length}`,
    )
    console.log(`\n  If an acknowledgement in docs/audits/a04-fixture-currency.json named the old digest, DELETE it — it is now obsolete.`)
}
