/**
 * Freeze the A04 concrete game as the canonical rendering fixture — by RUNNING the closure, not by
 * transcribing it.
 *
 * The first version of this fixture was hand-built from the closure run's printed output, and that is a
 * fork waiting to happen: the moment the engine changes, a hand-copied fixture keeps testing the old
 * game while claiming to be the current one. The project has already been bitten by a harness that
 * reproduced a pipeline *approximately*. So this runs the same stages as `run-first-game.ts`, in the same
 * order, and refuses to write anything unless the run is actually render-eligible.
 *
 * Run: npm run freeze:a04
 */
import fs from 'node:fs'
import path from 'node:path'

import { isStampedHalt } from '../derivation/emit'
import { runDerivation, runStages0to10 } from '../derivation/engine'
import { indexRegister } from '../derivation/register'
import { assembleResolvedGame } from '../derivation/resolved-game'
import { derivationInputFor, selectFor } from '../derivation/run-bounded-selection'
import { completeConcreteGame } from '../realization/assemble-concrete-game'
import { runPostRealizationGates } from '../realization/post-realization-gate'
import { checkRealization, isRefused, realize, Realized } from '../realization/realize'

const CHOICES = path.resolve(__dirname, '../../../../docs/audits/a04-realization-choices.json')
const OUT = path.resolve(__dirname, '../../../../docs/audits/a04-concrete-game-fixture.json')

const selection = selectFor('A04', null)
const input = derivationInputFor(selection)
const result = runDerivation(input)
if (isStampedHalt(result)) throw new Error('the run halted')

const staged: any = runStages0to10(input)
const index = indexRegister(input.register)
const resolved = assembleResolvedGame(result, staged.classes, index, input.contracts)
if (!resolved.coherence.realizationAuthorized) throw new Error('A04 is not realization-authorized; nothing to freeze')

const supplied = JSON.parse(fs.readFileSync(CHOICES, 'utf8'))
const realizationResult = realize(resolved, supplied.choices, supplied.instantiations, index, input.envelope)
if (isRefused(realizationResult)) throw new Error(`realization refused: ${realizationResult.because.join('; ')}`)
const realized = realizationResult as Realized

// Same order as the closure run: entail over the concrete game, THEN check it, THEN gate it.
const gateContext = { ...staged.gateContext, contracts: input.contracts }
const entailed = completeConcreteGame(gateContext, realized)

const checks = checkRealization(resolved, realized)
const accepted = !checks.nothingClosedWithoutAuthority.length && !checks.nothingLost.length && !checks.nothingInvented.length
const post = runPostRealizationGates(
    gateContext,
    resolved.coherence.postRealizationRequired.map(o => ({ checkId: o.checkId, clause: o.clause })),
    realized,
)

// **Refuse to freeze anything that is not the closed game.** A fixture that captured a failing run would
// quietly become the thing rendering is tested against.
if (!accepted) throw new Error(`realization acceptance FAILED: ${JSON.stringify(checks)}`)
if (!post.validated) throw new Error(`post-realization Gate A NOT PASSED: ${post.outstanding.join('; ')}`)

const fixture = {
    // **His instruction is recorded here verbatim, and it stays here.** The first generated version of this
    // file replaced it with a description of the generator, which deleted the owner's words from the
    // artifact they govern — the project's oldest failure mode, committed against a ruling. Regenerating the
    // fixture after a fix to the chain is a separate, deliberate act and does not retire the instruction:
    // rendering still reads this file and never a live run.
    note:
        'THE CANONICAL A04 RENDERING FIXTURE. Christian: "use the exact A04 concrete game from this closure ' +
        'run as the canonical rendering fixture. For this first test, do not reselect or re-realize it." So ' +
        'rendering reads THIS artifact and never a fresh run. Regenerated by `npm run freeze:a04` only when ' +
        'the chain itself is corrected — as on 1 October 2026, when the derived roster was found never to ' +
        'reach the concrete game — and never hand-edited. If a run would otherwise produce a different game, ' +
        'that is a separate finding and this file does not move.',
    provenance: resolved.provenance,
    closure: {
        preRealization: resolved.coherence.preRealization,
        realizationAuthorized: resolved.coherence.realizationAuthorized,
        postRealizationValidated: post.validated,
        renderEligible: accepted && post.validated,
    },
    envelope: {
        players: (input.envelope as any).players,
        lengthM: (input.envelope as any).area?.length_m ?? (input.envelope as any).lengthM,
        widthM: (input.envelope as any).area?.width_m ?? (input.envelope as any).widthM,
        durationMin: (input.envelope as any).duration_min ?? (input.envelope as any).durationMin,
        roles: (input.envelope as any).roles ?? {},
    },
    game: realized.game,
    record: realized.record,
    status: {
        derived: resolved.derived.map(d => ({ path: d.path, lineId: d.lineId, value: d.value })),
        choices: realized.record.choices.map(c => ({ path: c.path, lineId: c.lineId, value: c.value })),
        instantiations: realized.record.instantiations.map(i => ({ path: i.path, classId: i.classId, handle: i.handle, memberIndex: i.memberIndex, member: i.member })),
        entailed,
        geometry: realized.record.geometry,
        jointConditions: resolved.jointConditions,
        notEstablished: resolved.notEstablished.map(n => ({ path: n.path, lineId: n.lineId, reason: n.reason, declared: n.declared })),
    },
}

fs.writeFileSync(OUT, `${JSON.stringify(fixture, null, 1)}\n`, 'utf8')
console.log(`froze ${path.basename(OUT)}`)
console.log(`  render-eligible   ${fixture.closure.renderEligible ? 'YES' : 'NO'}`)
console.log(`  input digest      ${resolved.provenance.inputDigest}`)
console.log(`  derived ${fixture.status.derived.length} · choices ${fixture.status.choices.length} · instantiations ${fixture.status.instantiations.length} · entailed ${entailed.length} · geometry ${fixture.status.geometry.length}`)
