/**
 * Representative Intervention Library loader — Experience Design RC1.
 *
 * Canonical source: the workbook committed verbatim at
 * `back/data/experience-design/representative-intervention.rc1.xlsx`, projected completely into
 * `representative-intervention.rc1.json` (generated by `project-workbook.py` — never hand-edit).
 *
 * WHAT THIS LAYER IS FOR. Experience Design improves how an ALREADY-REPRESENTATIVE activity is
 * experienced. Christian's Runtime Decision Rules are explicit that it runs only after Representative
 * Validation succeeds, and that it "never compensates for non-representative activity design". So
 * nothing here can rescue a bad activity, and nothing here should try.
 *
 * WHAT IT MUST NOT DO, which shapes the whole module: interventions add representative demand, they
 * do not restrict player behaviour. The Preference Framework orders enhancement from enriching
 * affordances down to modifying interaction rules, with rule changes LAST. That ordering is a
 * knowledge decision and lives in the workbook and his documents — this loader exposes the knowledge
 * and refuses to rank it.
 *
 * THE GATE CHECKS DECLARED COUNTS, unlike the Session Planning Model. This workbook carries a
 * Metadata sheet declaring seven Intervention Categories and ten Representative Interventions, plus
 * the pilot limits — so the same discipline as the Knowledge Core libraries applies: if the workbook
 * and the projection disagree, that is a defined failure rather than a silent one.
 *
 * NOT WIRED TO GENERATION. Nothing consults this during activity assembly yet. That is deliberate,
 * and the same sequencing that worked for the Sport Module: prove the knowledge loads and validates
 * before letting it change an activity, so a behaviour change can be attributed to one thing.
 */
import workbook from './representative-intervention.rc1.json'

export type InterventionRow = Record<string, string | number | null>

interface InterventionWorkbook {
    source_workbook: string
    header_row: number
    registry: InterventionRow[]
    runtime_data: InterventionRow[]
    metadata: Record<string, string | number | null>
}

const WB = workbook as unknown as InterventionWorkbook

const OBJECT_TYPE_CATEGORY = 'Intervention Category'
const OBJECT_TYPE_INTERVENTION = 'Representative Intervention'

const text = (row: InterventionRow, column: string): string => {
    const value = row[column]
    return value === null || value === undefined ? '' : String(value).trim()
}

/** Workbook convention for multi-value cells on this sheet — semicolons, no spaces guaranteed. */
const list = (row: InterventionRow, column: string): string[] =>
    text(row, column)
        .split(';')
        .map((entry) => entry.trim())
        .filter(Boolean)

export interface InterventionCategory {
    id: string
    name: string
    definition: string
}

export interface RepresentativeIntervention {
    id: string
    categoryId: string
    name: string
    definition: string
    coachDescription: string
    /** Which canonical library owns the mechanism — the boundary back into the Knowledge Core. */
    ecologicalOwner: string
    representativeRationale: string
    primaryAffordanceIntent: string[]
    usageGuidance: string
    /** Eligibility, from the Runtime Data sheet. Empty arrays mean "no constraint declared". */
    learningStages: string[]
    challengeLevels: string[]
    sportTags: string[]
    affordanceTags: string[]
}

export interface InterventionIntegrityResult {
    valid: boolean
    errors: string[]
}

const registryRows = (objectType: string): InterventionRow[] =>
    WB.registry.filter((row) => text(row, 'Object Type') === objectType)

/**
 * Load-time integrity gate.
 *
 * Each check corresponds to a way Experience Design silently does nothing rather than failing:
 * an intervention whose category is missing can never be reached through its Stakes Variable, and
 * an intervention with no Runtime Data row has no eligibility so it can never be selected. Both look
 * exactly like "the runtime decided not to enhance this activity", which is a legitimate outcome —
 * so without these checks a broken row is indistinguishable from a working one.
 */
export function validateInterventionLibrary(data: InterventionWorkbook = WB): InterventionIntegrityResult {
    const errors: string[] = []
    const meta = data.metadata

    const categories = data.registry.filter((row) => text(row, 'Object Type') === OBJECT_TYPE_CATEGORY)
    const interventions = data.registry.filter((row) => text(row, 'Object Type') === OBJECT_TYPE_INTERVENTION)

    const declaredCategories = Number(meta['Intervention Categories'])
    const declaredInterventions = Number(meta['Representative Interventions'])
    if (!Number.isFinite(declaredCategories) || !Number.isFinite(declaredInterventions)) {
        errors.push('Metadata does not declare both object counts; the loader cannot verify the registry.')
    } else {
        if (categories.length !== declaredCategories) {
            errors.push(`Metadata declares ${declaredCategories} Intervention Categories but the registry holds ${categories.length}.`)
        }
        if (interventions.length !== declaredInterventions) {
            errors.push(
                `Metadata declares ${declaredInterventions} Representative Interventions but the registry holds ${interventions.length}.`
            )
        }
    }

    // An unrecognised Object Type would be silently dropped by both filters above.
    for (const row of data.registry) {
        const objectType = text(row, 'Object Type')
        if (objectType !== OBJECT_TYPE_CATEGORY && objectType !== OBJECT_TYPE_INTERVENTION) {
            errors.push(`Registry row "${text(row, 'ID')}" has unknown Object Type "${objectType}"; it would be ignored.`)
        }
    }

    const categoryIds = new Set<string>()
    for (const row of categories) {
        const id = text(row, 'ID')
        if (!id) {
            errors.push('An Intervention Category has no ID.')
            continue
        }
        if (categoryIds.has(id)) errors.push(`Duplicate Intervention Category "${id}".`)
        categoryIds.add(id)
        if (!text(row, 'Name')) errors.push(`Intervention Category "${id}" has no Name.`)
    }

    const eligibilityIds = new Set(data.runtime_data.map((row) => text(row, 'Object ID')))
    const interventionIds = new Set<string>()

    for (const row of interventions) {
        const id = text(row, 'ID')
        if (!id) {
            errors.push('A Representative Intervention has no ID.')
            continue
        }
        if (interventionIds.has(id)) errors.push(`Duplicate Representative Intervention "${id}".`)
        interventionIds.add(id)

        const parent = text(row, 'Parent ID')
        if (!categoryIds.has(parent)) {
            errors.push(
                `Intervention "${id}" has Parent ID "${parent}", which is not an Intervention Category. ` +
                    `It could never be reached through a Stakes Variable — and that looks identical to the runtime ` +
                    `choosing not to enhance the activity.`
            )
        }

        if (!eligibilityIds.has(id)) {
            errors.push(
                `Intervention "${id}" has no Runtime Data row, so it declares no eligibility and can never be ` +
                    `selected. Silently unselectable, not broken-looking.`
            )
        }

        // The coach has to be able to run it, and the rationale is what keeps it representative.
        for (const column of ['Name', 'Definition', 'Coach Description']) {
            if (!text(row, column)) errors.push(`Intervention "${id}" has no ${column}.`)
        }
    }

    for (const row of data.runtime_data) {
        const id = text(row, 'Object ID')
        if (!interventionIds.has(id)) {
            errors.push(`Runtime Data references "${id}", which is not a Representative Intervention in the registry.`)
        }
    }

    // Pilot limits are knowledge, declared in the workbook. A future revision that raises them is a
    // deliberate scope change, and the runtime should read them rather than assume one of each.
    for (const key of ['Maximum Representative Stakes Variables per Activity', 'Maximum Representative Interventions per Activity']) {
        const value = Number(meta[key]);
        if (!Number.isFinite(value) || value < 1) {
            errors.push(`Metadata "${key}" is missing or not a positive number; the runtime cannot know the pilot limit.`)
        }
    }

    return { valid: errors.length === 0, errors }
}

/**
 * Interventions whose ecological ownership is unresolved, reported rather than guessed.
 *
 * RI-010 carries "TBD" and two others are marked "(review)". Ownership decides which canonical
 * library governs the mechanism, so it is a knowledge decision — reporting keeps it visible instead
 * of letting an unowned intervention quietly behave as though it were settled.
 */
export function reportUnresolvedOwnership(data: InterventionWorkbook = WB): Array<{ id: string; owner: string }> {
    return data.registry
        .filter((row) => text(row, 'Object Type') === OBJECT_TYPE_INTERVENTION)
        .map((row) => ({ id: text(row, 'ID'), owner: text(row, 'Primary Ecological Owner') }))
        .filter((entry) => entry.owner === '' || /tbd|review/i.test(entry.owner))
}

/**
 * Learning Stage vocabulary used by this workbook, reported for comparison against IC-001's.
 *
 * RESOLVED, and kept as a guard. The workbook originally declared "Exploring", "Building" and
 * "Refining" — none of which matched the labels a coach actually selects, and no single rule bridged
 * them. Christian adopted IC-001's labels in response and added a `Learning Stage Source` declaration
 * naming that contract.
 *
 * This remains because the failure it caught is invisible: Runtime Decision 4 retrieves interventions
 * by Learning Stage compatibility, so if the vocabularies ever diverge again every intervention
 * silently fails to match and Experience Design does nothing — indistinguishable from correctly
 * deciding no enhancement was needed.
 */
export function reportLearningStageVocabulary(data: InterventionWorkbook = WB): string[] {
    const values = new Set<string>()
    for (const row of data.runtime_data) {
        for (const value of text(row, 'Learning Stage').split(';')) {
            const trimmed = value.trim()
            if (trimmed) values.add(trimmed)
        }
    }
    return [...values].sort()
}

function toIntervention(row: InterventionRow): RepresentativeIntervention {
    const id = text(row, 'ID')
    const eligibility = WB.runtime_data.find((r) => text(r, 'Object ID') === id)

    return {
        id,
        categoryId: text(row, 'Parent ID'),
        name: text(row, 'Name'),
        definition: text(row, 'Definition'),
        coachDescription: text(row, 'Coach Description'),
        ecologicalOwner: text(row, 'Primary Ecological Owner'),
        representativeRationale: text(row, 'Representative Rationale'),
        primaryAffordanceIntent: list(row, 'Primary Affordance Intent'),
        usageGuidance: text(row, 'Usage Guidance'),
        learningStages: eligibility ? list(eligibility, 'Learning Stage') : [],
        challengeLevels: eligibility ? list(eligibility, 'Challenge Level') : [],
        sportTags: eligibility ? list(eligibility, 'Sport Tags') : [],
        affordanceTags: eligibility ? list(eligibility, 'Affordance IDs/Tags') : [],
    }
}

export const representativeInterventionLibrary = {
    sourceWorkbook: WB.source_workbook,
    version: String(WB.metadata['Version'] ?? ''),
    /** Which contract the Learning Stage vocabulary comes from — added by Christian after our report. */
    learningStageSource: String(WB.metadata['Learning Stage Source'] ?? ''),
    /** Pilot limits, read from the workbook rather than assumed. */
    maxStakesVariablesPerActivity: Number(WB.metadata['Maximum Representative Stakes Variables per Activity'] ?? 1),
    maxInterventionsPerActivity: Number(WB.metadata['Maximum Representative Interventions per Activity'] ?? 1),

    categories: (): InterventionCategory[] =>
        registryRows(OBJECT_TYPE_CATEGORY).map((row) => ({
            id: text(row, 'ID'),
            name: text(row, 'Name'),
            definition: text(row, 'Definition'),
        })),

    interventions: (): RepresentativeIntervention[] => registryRows(OBJECT_TYPE_INTERVENTION).map(toIntervention),

    intervention: (id: string): RepresentativeIntervention | undefined => {
        const row = registryRows(OBJECT_TYPE_INTERVENTION).find((r) => text(r, 'ID') === id)
        return row ? toIntervention(row) : undefined
    },

    /**
     * Interventions belonging to a Stakes Variable, by category NAME rather than id.
     *
     * The Decision Rules name the seven variables in coach-ish terms ("Pressure", "Information"),
     * and those names are the category names — so matching on name keeps the runtime speaking the
     * document's vocabulary instead of translating to ids the document never mentions.
     */
    interventionsForStakesVariable: (variableName: string): RepresentativeIntervention[] => {
        const category = registryRows(OBJECT_TYPE_CATEGORY).find(
            (row) => text(row, 'Name').toLowerCase() === variableName.trim().toLowerCase()
        )
        if (!category) return []
        const categoryId = text(category, 'ID')
        return registryRows(OBJECT_TYPE_INTERVENTION)
            .filter((row) => text(row, 'Parent ID') === categoryId)
            .map(toIntervention)
    },
}
