import type { TestLibraryV0AffordanceLens } from './types'

/** Test Library V0 — affordance lenses (from csv/affordance-lenses.csv) */
export const TEST_LIBRARY_V0_AFFORDANCE_LENSES: TestLibraryV0AffordanceLens[] = [
  {
    id: "tl-v0-lens-line-breaking-opportunity",
    title: "Line-Breaking Opportunity",
    description: "Opportunity for players to perceive and act on options that penetrate defensive lines",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration through perception of gaps",
    contextualAudit: "Avoid forcing forward passes or direction of play",
    suggestedConstraintPrompt: "Use scoring incentives and defensive pressure to invite recognition of line-breaking opportunities",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up","final_third"],
    designIntent: "Penetrate into final third",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward successful penetration leading to advantage or shot","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning","compact shape with passing lanes appearing"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "penetrating pass", "penetration", "penetrate", "split defenders",
      "line-breaking", "line breaking", "break the line", "break defensive line",
      "between the lines", "through pass", "through ball",
      "forward pass", "play forward", "play through",
      "find the seam", "find the gap", "exploit gap",
      "dribble through", "dribble past line",
      "third-man run", "third man", "wall pass forward",
    ],
  },
  {
    id: "tl-v0-lens-space-exploitation-opportunity",
    title: "Space Exploitation Opportunity",
    description: "Opportunity for players to recognize and use available space to advance play",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages spatial awareness and adaptability",
    contextualAudit: "Avoid rigid positioning or fixed zone occupation",
    suggestedConstraintPrompt: "Use spatial incentives and defensive imbalance to invite space recognition",
    category: "Create Space",
    gameTemplateAnchor: ["build_up","transition"],
    designIntent: "Use width and depth effectively",
    constraintSupport: ["structural","consequence"],
    exampleConsequencePatterns: ["reward effective use of space that leads to progression or finish","reward quick transition after regain or turnover"],
    visibilityTriggers: ["space opening or closing","time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "exploit space", "exploit open space", "use space", "use open space",
      "attack space", "attack open space", "find space",
      "use width", "use depth", "stretch the field",
      "switch to open side", "switch the play to open",
      "play into space", "run into space",
    ],
  },
  {
    id: "tl-v0-lens-space-creation-opportunity",
    title: "Space Creation Opportunity",
    description: "Opportunity for players to manipulate defenders to open new spaces",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages movement and displacement",
    contextualAudit: "Avoid choreographed or pre-planned movement patterns",
    suggestedConstraintPrompt: "Use defensive pressure and movement incentives to invite space creation",
    category: "Create Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Disorganize defensive shape",
    constraintSupport: ["structural","shaping","consequence"],
    exampleConsequencePatterns: ["reward effective use of space that leads to progression or finish","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["space opening or closing","pressure level and defender positioning"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "create space", "open space", "make space", "drag defenders",
      "drawing defenders out", "draw defenders", "pull defenders out",
      "disorganize defense", "disrupt defensive shape", "unbalance defenders",
      "movement off ball", "off-ball movement", "make runs",
      "decoy run", "support run", "dummy run",
      "manipulate defenders", "stretch defense",
    ],
  },
  {
    id: "tl-v0-lens-possession-stability-opportunity",
    title: "Possession Stability Opportunity",
    description: "Opportunity for players to retain control under pressure",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages composure and support play",
    contextualAudit: "Avoid pass limits or restrictive rules",
    suggestedConstraintPrompt: "Use defensive rewards and pressure to invite stable possession decisions",
    category: "Maintain Possession",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Retain possession under pressure",
    constraintSupport: ["shaping"],
    exampleConsequencePatterns: ["reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning","numerical advantage or support angle"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "retain possession", "keep possession", "ball retention", "secure possession",
      "possession under pressure", "composure under pressure",
      "play through pressure", "escape pressure", "play out of pressure",
      "support angles", "support distances", "supporting players",
      "build out", "build up", "play out from back",
      "circulate ball", "circulate possession", "ball circulation",
    ],
  },
  {
    id: "tl-v0-lens-transition-attack-opportunity",
    title: "Transition Attack Opportunity",
    description: "Opportunity to act quickly before defense organizes",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages recognition of transition moments",
    contextualAudit: "Avoid forcing speed or rushed decisions",
    suggestedConstraintPrompt: "Use time-based incentives and transition rewards to invite quick attacking decisions",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Exploit transition moments",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward quick transition after regain or turnover"],
    visibilityTriggers: ["time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "transition attack", "attack in transition", "fast attack",
      "counter attack", "counter-attack", "quick counter",
      "after winning ball", "after regain", "after turnover",
      "exploit disorganized defense", "attack before defense recovers",
      "attack quickly", "play forward fast", "break forward",
    ],
  },
  {
    id: "tl-v0-lens-finishing-opportunity",
    title: "Finishing Opportunity",
    description: "Opportunity to recognize and act on goal-scoring chances",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages timing and decision-making in scoring",
    contextualAudit: "Avoid artificial shooting constraints",
    suggestedConstraintPrompt: "Use scoring variations and defensive pressure to invite finishing decisions",
    category: "Finish",
    gameTemplateAnchor: ["final_third"],
    designIntent: "Convert chances",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward chances or goals created from the target action","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "finishing", "finish", "convert chances", "convert chance",
      "scoring chance", "scoring opportunity", "shot on goal",
      "good shot", "get off a shot", "first time finish",
      "in front of goal", "near goal area", "near opponent goal",
      "in the box", "in penalty box", "around penalty box",
      "shoot", "shooting", "shot",
    ],
  },
  {
    id: "tl-v0-lens-delay-or-deny-opportunity",
    title: "Delay or Deny Opportunity",
    description: "Opportunity to slow or prevent attacking progression",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages disruption and control",
    contextualAudit: "Avoid over-restricting attacking options",
    suggestedConstraintPrompt: "Use defensive rewards to invite delaying and denial behaviors",
    category: "Delay or Deny",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Slow attacking progression",
    constraintSupport: ["shaping"],
    exampleConsequencePatterns: ["use consequence only if it clarifies value without forcing behavior"],
    visibilityTriggers: ["opponent movement and changing space"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "delay attacker", "delay opponent", "delay the attack",
      "deny forward pass", "deny progress", "deny the option",
      "force play backward", "force play wide", "force opponent backward",
      "channel opponent", "shepherd attacker",
      "defensive denial", "defensive delay",
    ],
  },
  {
    id: "tl-v0-lens-regain-opportunity",
    title: "Regain Opportunity",
    description: "Opportunity to win possession from the opponent",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages anticipation and pressure",
    contextualAudit: "Avoid forced pressing triggers",
    suggestedConstraintPrompt: "Use interception and turnover rewards to invite regain moments",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Win the ball back",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward quick transition after regain or turnover","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning","time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "regain", "regain possession", "win ball back", "win the ball back",
      "force turnover", "cause turnover", "force a turnover",
      "press", "press to regain", "pressing", "pressing to regain",
      "intercept", "interception", "anticipate the pass",
      "team defensive pressure", "applied pressure", "win ball",
      "press triggers", "when to press",
    ],
  },
  {
    id: "tl-v0-lens-space-protection-opportunity",
    title: "Space Protection Opportunity",
    description: "Opportunity to maintain defensive shape and deny space",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages compactness and positioning",
    contextualAudit: "Avoid rigid positioning rules",
    suggestedConstraintPrompt: "Use defensive rewards to invite spatial protection behaviors",
    category: "Protect Space",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Maintain compact defensive shape",
    constraintSupport: ["structural"],
    exampleConsequencePatterns: ["use consequence only if it clarifies value without forcing behavior"],
    visibilityTriggers: ["space opening or closing"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "protect space", "defensive shape", "stay compact", "compact shape",
      "deny space", "deny dangerous space",
      "withdrawn defense", "low block", "defensive block",
      "cover space", "cover behind", "cover for teammate",
      "defending box", "defending goal area",
    ],
  },
  {
    id: "tl-v0-lens-recovery-opportunity",
    title: "Recovery Opportunity",
    description: "Opportunity to reorganize defensively after disruption",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages recovery and reorganization",
    contextualAudit: "Avoid forced recovery patterns",
    suggestedConstraintPrompt: "Use time-based defensive incentives to invite recovery decisions",
    category: "Recover Shape",
    gameTemplateAnchor: ["transition"],
    designIntent: "Reorganize defensively after transition",
    constraintSupport: ["structural","shaping","consequence"],
    exampleConsequencePatterns: ["reward quick transition after regain or turnover"],
    visibilityTriggers: ["time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
    coachVocabulary: [
      "recover shape", "recovery", "recover defensive shape",
      "tracking runs", "track back", "tracking back", "track the runner",
      "reorganize defense", "reorganize defensively", "regain shape",
      "defensive transition", "transition to defense",
      "delay counter", "defending counterattack", "defending counter attack",
    ],
  },
]
