import type { TestLibraryV0AffordanceLens } from './types'

/** Test Library V0 — affordance lenses (from csv/affordance-lenses.csv) */
export const TEST_LIBRARY_V0_AFFORDANCE_LENSES: TestLibraryV0AffordanceLens[] = [
  {
    id: "tl-v0-lens-line-breaking-opportunity",
    title: "Line-Breaking Opportunity",
    description: "Opportunity for players to perceive and act on options that penetrate defensive lines",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration through perception of gaps",
    contextualAudit: "Avoid forcing forward passes or direction of play",
    suggestedConstraintPrompt: "Use scoring incentives and defensive pressure to invite recognition of line-breaking opportunities",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up","final_third"],
    designIntent: "Penetrate into final third",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward successful penetration leading to advantage or shot","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning","compact shape with passing lanes appearing"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-space-exploitation-opportunity",
    title: "Space Exploitation Opportunity",
    description: "Opportunity for players to recognize and use available space to advance play",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages spatial awareness and adaptability",
    contextualAudit: "Avoid rigid positioning or fixed zone occupation",
    suggestedConstraintPrompt: "Use spatial incentives and defensive imbalance to invite space recognition",
    category: "Create Space",
    gameTemplateAnchor: ["build_up","transition"],
    designIntent: "Use width and depth effectively",
    constraintSupport: ["structural","consequence"],
    exampleConsequencePatterns: ["reward effective use of space that leads to progression or finish","reward quick transition after regain or turnover"],
    visibilityTriggers: ["space opening or closing","time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-space-creation-opportunity",
    title: "Space Creation Opportunity",
    description: "Opportunity for players to manipulate defenders to open new spaces",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages movement and displacement",
    contextualAudit: "Avoid choreographed or pre-planned movement patterns",
    suggestedConstraintPrompt: "Use defensive pressure and movement incentives to invite space creation",
    category: "Create Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Disorganize defensive shape",
    constraintSupport: ["structural","shaping","consequence"],
    exampleConsequencePatterns: ["reward effective use of space that leads to progression or finish","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["space opening or closing","pressure level and defender positioning"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-possession-stability-opportunity",
    title: "Possession Stability Opportunity",
    description: "Opportunity for players to retain control under pressure",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages composure and support play",
    contextualAudit: "Avoid pass limits or restrictive rules",
    suggestedConstraintPrompt: "Use defensive rewards and pressure to invite stable possession decisions",
    category: "Maintain Possession",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Retain possession under pressure",
    constraintSupport: ["shaping"],
    exampleConsequencePatterns: ["reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning","numerical advantage or support angle"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-transition-attack-opportunity",
    title: "Transition Attack Opportunity",
    description: "Opportunity to act quickly before defense organizes",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages recognition of transition moments",
    contextualAudit: "Avoid forcing speed or rushed decisions",
    suggestedConstraintPrompt: "Use time-based incentives and transition rewards to invite quick attacking decisions",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Exploit transition moments",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward quick transition after regain or turnover"],
    visibilityTriggers: ["time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-finishing-opportunity",
    title: "Finishing Opportunity",
    description: "Opportunity to recognize and act on goal-scoring chances",
    type: "affordance",
    affordanceTagGroup: "Attacking",
    notes: "Encourages timing and decision-making in scoring",
    contextualAudit: "Avoid artificial shooting constraints",
    suggestedConstraintPrompt: "Use scoring variations and defensive pressure to invite finishing decisions",
    category: "Finish",
    gameTemplateAnchor: ["final_third"],
    designIntent: "Convert chances",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward chances or goals created from the target action","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-delay-or-deny-opportunity",
    title: "Delay or Deny Opportunity",
    description: "Opportunity to slow or prevent attacking progression",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages disruption and control",
    contextualAudit: "Avoid over-restricting attacking options",
    suggestedConstraintPrompt: "Use defensive rewards to invite delaying and denial behaviors",
    category: "Delay or Deny",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Slow attacking progression",
    constraintSupport: ["shaping"],
    exampleConsequencePatterns: ["use consequence only if it clarifies value without forcing behavior"],
    visibilityTriggers: ["opponent movement and changing space"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-regain-opportunity",
    title: "Regain Opportunity",
    description: "Opportunity to win possession from the opponent",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages anticipation and pressure",
    contextualAudit: "Avoid forced pressing triggers",
    suggestedConstraintPrompt: "Use interception and turnover rewards to invite regain moments",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Win the ball back",
    constraintSupport: ["shaping","consequence"],
    exampleConsequencePatterns: ["reward quick transition after regain or turnover","reward regain in target area or disruption leading to attack"],
    visibilityTriggers: ["pressure level and defender positioning","time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-space-protection-opportunity",
    title: "Space Protection Opportunity",
    description: "Opportunity to maintain defensive shape and deny space",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages compactness and positioning",
    contextualAudit: "Avoid rigid positioning rules",
    suggestedConstraintPrompt: "Use defensive rewards to invite spatial protection behaviors",
    category: "Protect Space",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Maintain compact defensive shape",
    constraintSupport: ["structural"],
    exampleConsequencePatterns: ["use consequence only if it clarifies value without forcing behavior"],
    visibilityTriggers: ["space opening or closing"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
  {
    id: "tl-v0-lens-recovery-opportunity",
    title: "Recovery Opportunity",
    description: "Opportunity to reorganize defensively after disruption",
    type: "affordance",
    affordanceTagGroup: "Defensive",
    notes: "Encourages recovery and reorganization",
    contextualAudit: "Avoid forced recovery patterns",
    suggestedConstraintPrompt: "Use time-based defensive incentives to invite recovery decisions",
    category: "Recover Shape",
    gameTemplateAnchor: ["transition"],
    designIntent: "Reorganize defensively after transition",
    constraintSupport: ["structural","shaping","consequence"],
    exampleConsequencePatterns: ["reward quick transition after regain or turnover"],
    visibilityTriggers: ["time pressure or transition moment"],
    logicUsageNote: "Use this affordance as a design anchor. Match to archetype first, then choose constraints that shape visibility and, only when useful, add a consequence layer.",
  },
]
