import type { TestLibraryV0Archetype } from './types'

/** Test Library V0 — archetypes / game forms (from csv/archetypes.csv) */
export const TEST_LIBRARY_V0_ARCHETYPES: TestLibraryV0Archetype[] = [
  {
    id: "GF1",
    game_form_id: "GF1",
    game_form_name: "End Zone Games",
    objective: "Move ball into a target zone",
    interaction_structure: "Directional progression with scoring zones",
    directionality_type: "High directional",
    phase_of_play: "Final third / build-up",
    player_structure_logic: "Even or slight overload",
    typical_affordances: ["A1","A2","A6"],
    recommended_constraint_types: ["Scoring Incentive","Spatial Condition"],
    representative_design_notes: "Use end zones to invite timing and penetration without forcing entry",
    primaryAffordances: ["create_space","exploit_space","finish"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF2",
    game_form_id: "GF2",
    game_form_name: "Directional Possession Games",
    objective: "Maintain possession with forward intent",
    interaction_structure: "Continuous directional circulation",
    directionality_type: "Moderate directional",
    phase_of_play: "Build-up",
    player_structure_logic: "Even numbers",
    typical_affordances: ["A1","A4","A2"],
    recommended_constraint_types: ["Defensive Reward","Spatial Condition"],
    representative_design_notes: "Encourage progression without restricting passing options",
    primaryAffordances: ["maintain_possession","create_space","break_lines"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "high",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["reward line-breaking pass leading to shot","bonus for switching play then scoring"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF3",
    game_form_id: "GF3",
    game_form_name: "Positional Play Games",
    objective: "Maintain structure while creating advantages",
    interaction_structure: "Structured positional grid play",
    directionality_type: "Moderate directional",
    phase_of_play: "Build-up",
    player_structure_logic: "Even or overload",
    typical_affordances: ["A2","A3","A4"],
    recommended_constraint_types: ["Spatial Condition","Defensive Reward"],
    representative_design_notes: "Focus on relationships and support rather than fixed positioning rules",
    primaryAffordances: ["create_space","exploit_space","maintain_possession"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "high",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["reward line-breaking pass leading to shot","bonus for switching play then scoring"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF4",
    game_form_id: "GF4",
    game_form_name: "Transition Games",
    objective: "Exploit moments after turnover",
    interaction_structure: "Fast phase-switching play",
    directionality_type: "High directional",
    phase_of_play: "Transition",
    player_structure_logic: "Uneven during transitions",
    typical_affordances: ["A5","A8","A1"],
    recommended_constraint_types: ["Transition Trigger","Time Condition"],
    representative_design_notes: "Design for immediate decision-making after regain",
    primaryAffordances: ["exploit_space","fast_attack","regain"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "high",
    constraintFit_consequence: "high",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["double points for quick goal","reward regain leading to shot"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF5",
    game_form_id: "GF5",
    game_form_name: "Overload Games",
    objective: "Create and exploit numerical advantage",
    interaction_structure: "Local overload interactions",
    directionality_type: "Variable directional",
    phase_of_play: "All phases",
    player_structure_logic: "Intentional overload/underload",
    typical_affordances: ["A2","A3","A1"],
    recommended_constraint_types: ["Spatial Condition","Scoring Incentive"],
    representative_design_notes: "Allow recognition of advantage rather than forcing use of overload",
    primaryAffordances: ["create_space","exploit_space"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF6",
    game_form_id: "GF6",
    game_form_name: "Target Games",
    objective: "Play into or through key player/area",
    interaction_structure: "Focused progression through target",
    directionality_type: "High directional",
    phase_of_play: "Final third / build-up",
    player_structure_logic: "Neutral or target player",
    typical_affordances: ["A1","A3","A6"],
    recommended_constraint_types: ["Scoring Incentive","Defensive Reward"],
    representative_design_notes: "Targets should invite play, not require forced passes",
    primaryAffordances: ["finish","break_lines"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF7",
    game_form_id: "GF7",
    game_form_name: "Channel Games",
    objective: "Use spatial lanes effectively",
    interaction_structure: "Multi-lane directional play",
    directionality_type: "High directional",
    phase_of_play: "Build-up / final third",
    player_structure_logic: "Even distribution",
    typical_affordances: ["A2","A1","A3"],
    recommended_constraint_types: ["Spatial Condition","Scoring Incentive"],
    representative_design_notes: "Channels guide perception but must remain optional",
    primaryAffordances: ["finish","break_lines"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF8",
    game_form_id: "GF8",
    game_form_name: "Pressing & Regain Games",
    objective: "Win ball back under defined conditions",
    interaction_structure: "Defensive pressure-focused play",
    directionality_type: "Reactive directional",
    phase_of_play: "Defensive / transition",
    player_structure_logic: "Even or overload defense",
    typical_affordances: ["A8","A7","A10"],
    recommended_constraint_types: ["Defensive Reward","Transition Trigger"],
    representative_design_notes: "Encourage pressing through reward, not forced triggers",
    primaryAffordances: ["exploit_space","fast_attack","regain"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "high",
    constraintFit_consequence: "high",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["double points for quick goal","reward regain leading to shot"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF9",
    game_form_id: "GF9",
    game_form_name: "Finishing Games",
    objective: "Create and convert scoring chances",
    interaction_structure: "Final third attacking play",
    directionality_type: "High directional",
    phase_of_play: "Final third",
    player_structure_logic: "Even or attacking overload",
    typical_affordances: ["A6","A1","A2"],
    recommended_constraint_types: ["Scoring Incentive","Time Condition"],
    representative_design_notes: "Emphasize timing and decision-making in scoring situations",
    primaryAffordances: ["create_space","exploit_space","finish"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
  {
    id: "GF10",
    game_form_id: "GF10",
    game_form_name: "Constraint-Driven Free Play",
    objective: "Open play with light constraints",
    interaction_structure: "Free-flowing play",
    directionality_type: "Variable",
    phase_of_play: "All phases",
    player_structure_logic: "Flexible",
    typical_affordances: ["A2","A3","A5"],
    recommended_constraint_types: ["Any (balanced mix)"],
    representative_design_notes: "Maintain representativeness with minimal but meaningful constraints",
    primaryAffordances: ["create_space"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
  },
]
