import type { TestLibraryV0Archetype } from './types'

/** Test Library V0 — archetypes / game forms (from csv/archetypes.csv) */
export const TEST_LIBRARY_V0_ARCHETYPES: TestLibraryV0Archetype[] = [
  {
    id: "GF1",
    game_form_id: "GF1",
    game_form_name: "End Zone Games",
    objective: "Move ball into a target zone",
    interaction_structure: "Directional progression with scoring zones",
    directionality_type: "High directional",
    phase_of_play: "Final third / build-up",
    player_structure_logic: "Even or slight overload",
    typical_affordances: ["A1","A2","A6"],
    recommended_constraint_types: ["Scoring Incentive","Spatial Condition"],
    representative_design_notes: "Use end zones to invite timing and penetration without forcing entry",
    primaryAffordances: ["create_space","exploit_space","finish"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "end zone", "target zone", "score in zone", "advance ball", "enter the box",
      "withdrawn defense", "low block", "park the bus", "compact defense",
      "deep block", "break compact defense", "create scoring chance",
      "near opponent goal", "attacking third entry", "opponent goal area",
    ],
    setupGuidance: [
      "Mark target zones at both ends of the field (typical: a band 5-10m deep across the full width).",
      "Field divided into build-up area, mid area, and the two target end zones.",
      "Field dimensions scale with player count (typical: 40x30m for 8 players, up to 60x40m for 14+).",
    ],
  },
  {
    id: "GF2",
    game_form_id: "GF2",
    game_form_name: "Directional Possession Games",
    objective: "Maintain possession with forward intent",
    interaction_structure: "Continuous directional circulation",
    directionality_type: "Moderate directional",
    phase_of_play: "Build-up",
    player_structure_logic: "Even numbers",
    typical_affordances: ["A1","A4","A2"],
    recommended_constraint_types: ["Defensive Reward","Spatial Condition"],
    representative_design_notes: "Encourage progression without restricting passing options",
    primaryAffordances: ["maintain_possession","create_space","break_lines"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "high",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["reward line-breaking pass leading to shot","bonus for switching play then scoring"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "build out", "build up", "build-up", "playing out", "play out from the back",
      "circulate possession", "ball circulation", "retain possession", "ball retention",
      "midfielder", "midfielders", "center midfielder", "central midfielder",
      "middle third", "mid third", "third to third", "attacking third",
      "switch play", "switch the attack", "switching", "change of direction",
      "support angles", "support distances", "passing options",
      "play through pressure", "escape pressure", "secure possession",
      "penetrating pass", "forward pass", "line-breaking pass", "split defenders",
      "between the lines", "find the seam", "find the gap",
      "passing combinations", "combination play", "using one another",
      "dribble out of pressure", "carry the ball forward",
    ],
    setupGuidance: [
      "Rectangular field with a directional target line or zone at one end (typical: 40-60m long, 25-40m wide).",
      "Teams attack in the same direction, building from their own end toward the target.",
      "Restart conditions: ball out of play restarts from the team that didn't touch it last.",
    ],
  },
  {
    id: "GF3",
    game_form_id: "GF3",
    game_form_name: "Positional Play Games",
    objective: "Maintain structure while creating advantages",
    interaction_structure: "Structured positional grid play",
    directionality_type: "Moderate directional",
    phase_of_play: "Build-up",
    player_structure_logic: "Even or overload",
    typical_affordances: ["A2","A3","A4"],
    recommended_constraint_types: ["Spatial Condition","Defensive Reward"],
    representative_design_notes: "Focus on relationships and support rather than fixed positioning rules",
    primaryAffordances: ["create_space","exploit_space","maintain_possession"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "high",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["reward line-breaking pass leading to shot","bonus for switching play then scoring"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "positional play", "positional structure", "positional advantage",
      "free man", "free player in zone", "third-man run", "third man",
      "rotations", "rotation", "rotate positions", "interchange",
      "support shape", "shape under pressure", "compact shape",
      "find the free player", "create overload", "numerical advantage",
      "build through structure", "play between lines", "between the lines",
      "midfielders", "central midfielders", "build out",
    ],
    setupGuidance: [
      "Field divided into a positional grid (typical: 3 horizontal zones x 3 vertical channels = 9 cells).",
      "Players reference the grid for positional shape but move freely; the grid is a visual scaffold.",
      "Field dimensions scale to player count (typical: 50x35m for 8-10 outfield players).",
    ],
  },
  {
    id: "GF4",
    game_form_id: "GF4",
    game_form_name: "Transition Games",
    objective: "Exploit moments after turnover",
    interaction_structure: "Fast phase-switching play",
    directionality_type: "High directional",
    phase_of_play: "Transition",
    player_structure_logic: "Uneven during transitions",
    typical_affordances: ["A5","A8","A1"],
    recommended_constraint_types: ["Transition Trigger","Time Condition"],
    representative_design_notes: "Design for immediate decision-making after regain",
    primaryAffordances: ["exploit_space","fast_attack","regain"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "high",
    constraintFit_consequence: "high",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["double points for quick goal","reward regain leading to shot"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "transition", "transition moment", "transition attack", "fast break",
      "counter attack", "counter-attack", "counter", "quick attack",
      "after turnover", "after winning ball", "after losing ball",
      "exploit transition", "attack quickly", "play forward fast",
      "defensive counter", "defending counterattack", "defending counter attack",
      "overloaded numbers", "outnumbered defense",
      "win possession and attack", "attack before defense organizes",
      "transitioning from defense", "going from defense to attack",
    ],
    setupGuidance: [
      "Two-goal or two-target field with a midline marker; transition moment defined as possession change at any point.",
      "Numerical asymmetry can be introduced (e.g., 4v6 in defending half) when the goal is defending under overload.",
      "Restart conditions chain into immediate live play — no stoppage on turnover unless ball is out of play.",
    ],
  },
  {
    id: "GF5",
    game_form_id: "GF5",
    game_form_name: "Overload Games",
    objective: "Create and exploit numerical advantage",
    interaction_structure: "Local overload interactions",
    directionality_type: "Variable directional",
    phase_of_play: "All phases",
    player_structure_logic: "Intentional overload/underload",
    typical_affordances: ["A2","A3","A1"],
    recommended_constraint_types: ["Spatial Condition","Scoring Incentive"],
    representative_design_notes: "Allow recognition of advantage rather than forcing use of overload",
    primaryAffordances: ["create_space","exploit_space"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "overload", "numerical advantage", "create overload", "exploit overload",
      "extra player", "free player", "outnumber", "outnumbered",
      "2v1", "3v2", "4v3", "small-sided overload",
      "use the overload", "find the free man",
      "switch play to overload", "play through overload",
    ],
    setupGuidance: [
      "Build numerical asymmetry into the team structure (e.g., 6v4, 5v3, or a side with one neutral that always plays with the team in possession).",
      "Mark the contest area; field size sets the difficulty (tighter = harder for the overloaded side, wider = easier).",
      "Coach can vary the asymmetry between rounds to shift the challenge between attackers and defenders.",
    ],
  },
  {
    id: "GF6",
    game_form_id: "GF6",
    game_form_name: "Target Games",
    objective: "Play into or through key player/area",
    interaction_structure: "Focused progression through target",
    directionality_type: "High directional",
    phase_of_play: "Final third / build-up",
    player_structure_logic: "Neutral or target player",
    typical_affordances: ["A1","A3","A6"],
    recommended_constraint_types: ["Scoring Incentive","Defensive Reward"],
    representative_design_notes: "Targets should invite play, not require forced passes",
    primaryAffordances: ["finish","break_lines"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "target player", "target forward", "target striker", "playing to target",
      "connect to target", "feed the target", "into the striker",
      "key player", "focal point", "playing through target",
      "hold-up play", "hold up the ball", "lay off to target",
      "wall pass", "give and go through target",
    ],
    setupGuidance: [
      "Designate target player(s) positioned at one or both ends of the field (typically wearing contrasting bibs).",
      "Target players have a restricted movement area (e.g., a 10x10m box) or can roam — coach's choice.",
      "Connecting to the target and continuing the play from there is the central contest.",
    ],
  },
  {
    id: "GF7",
    game_form_id: "GF7",
    game_form_name: "Channel Games",
    objective: "Use spatial lanes effectively",
    interaction_structure: "Multi-lane directional play",
    directionality_type: "High directional",
    phase_of_play: "Build-up / final third",
    player_structure_logic: "Even distribution",
    typical_affordances: ["A2","A1","A3"],
    recommended_constraint_types: ["Spatial Condition","Scoring Incentive"],
    representative_design_notes: "Channels guide perception but must remain optional",
    primaryAffordances: ["finish","break_lines"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "channels", "wide channel", "half-space", "central corridor",
      "use width", "use the wings", "wing play", "wide play",
      "exploit wide areas", "switch to wide", "spread the play",
      "lane", "lanes", "open channel", "open lane",
      "wing attack", "stretch the field",
    ],
    setupGuidance: [
      "Field divided lengthwise into 3 or 5 channels (left wide, left half-space, central, right half-space, right wide).",
      "Channel boundaries marked with cones along the field's length.",
      "Channels guide perception but don't restrict movement; players choose which channel to attack through.",
    ],
  },
  {
    id: "GF8",
    game_form_id: "GF8",
    game_form_name: "Pressing & Regain Games",
    objective: "Win ball back under defined conditions",
    interaction_structure: "Defensive pressure-focused play",
    directionality_type: "Reactive directional",
    phase_of_play: "Defensive / transition",
    player_structure_logic: "Even or overload defense",
    typical_affordances: ["A8","A7","A10"],
    recommended_constraint_types: ["Defensive Reward","Transition Trigger"],
    representative_design_notes: "Encourage pressing through reward, not forced triggers",
    primaryAffordances: ["exploit_space","fast_attack","regain"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "high",
    constraintFit_consequence: "high",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["double points for quick goal","reward regain leading to shot"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "press", "pressing", "high press", "counter-press", "counter press",
      "team defensive pressure", "team pressure", "applying pressure",
      "win the ball back", "win ball back", "regain possession",
      "cause turnover", "force turnover", "force a turnover",
      "press triggers", "pressing triggers", "when to press",
      "defensive shape", "defensive recovery", "recover shape",
      "press as a team", "coordinated press",
    ],
    setupGuidance: [
      "Field divided into pressing third and defending third with a marked midline.",
      "Game starts with one team in possession in their own half; the pressing team's task is to win the ball within the pressing area.",
      "Restart conditions chain: regain → immediate attack; failed press → defending team continues attack.",
    ],
  },
  {
    id: "GF9",
    game_form_id: "GF9",
    game_form_name: "Finishing Games",
    objective: "Create and convert scoring chances",
    interaction_structure: "Final third attacking play",
    directionality_type: "High directional",
    phase_of_play: "Final third",
    player_structure_logic: "Even or attacking overload",
    typical_affordances: ["A6","A1","A2"],
    recommended_constraint_types: ["Scoring Incentive","Time Condition"],
    representative_design_notes: "Emphasize timing and decision-making in scoring situations",
    primaryAffordances: ["create_space","exploit_space","finish"],
    secondaryAffordances: [],
    constraintFit_structural: "high",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    coachVocabulary: [
      "finishing", "scoring chance", "create scoring chance",
      "shot", "shots on goal", "shooting", "shoot",
      "convert chance", "convert chances", "finish the chance",
      "near opponent goal", "around opponent box", "in the box",
      "penalty box area", "final third", "in front of goal",
      "good shot", "get off a shot", "first time finish",
      "withdrawn opponent", "low block scoring",
    ],
    setupGuidance: [
      "Final-third field setup with full-size or scaled goals at both ends, goalkeepers active.",
      "Attacking team starts in build-up area; field length keeps action concentrated in the final third (typical: 30-40m from box to halfway).",
      "Restart conditions chain quickly to maintain finishing-context tempo.",
    ],
  },
  {
    id: "GF10",
    game_form_id: "GF10",
    game_form_name: "Constraint-Driven Free Play",
    objective: "Open play with light constraints",
    interaction_structure: "Free-flowing play",
    directionality_type: "Variable",
    phase_of_play: "All phases",
    player_structure_logic: "Flexible",
    typical_affordances: ["A2","A3","A5"],
    recommended_constraint_types: ["Any (balanced mix)"],
    representative_design_notes: "Maintain representativeness with minimal but meaningful constraints",
    primaryAffordances: ["create_space"],
    secondaryAffordances: [],
    constraintFit_structural: "medium",
    constraintFit_shaping: "medium",
    constraintFit_consequence: "medium",
    recommendedConstraintTypes: ["structural","shaping","consequence"],
    exampleConstraintPatterns: ["zones or channels","restart conditions","time pressure","support rules"],
    exampleIncentivePatterns: ["bonus for achieving target outcome linked to affordance"],
    logicUsageNote: "Select this archetype when its structure naturally produces the target affordance; then choose constraints by role (foundation, shaping, consequence).",
    setupGuidance: [
      "Open field — no fixed positional structure beyond what the selected constraints impose.",
      "Field dimensions and team numbers chosen to match the constraint package's intent.",
      "Restart conditions stay live; coach lets the constraints shape the contest rather than adding fixed rules.",
    ],
  },
]
