import type { TestLibraryV0Constraint } from './types'

/** Test Library V0 — constraints (from csv/constraints.csv) */
export const TEST_LIBRARY_V0_CONSTRAINTS: TestLibraryV0Constraint[] = [
  {
    id: "tl-v0-constraint-progression-bonus",
    title: "Progression Bonus",
    description: "Reward advancement into attacking areas through successful progression",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration",
    contextualAudit: "Avoid forcing direction",
    suggestedConstraintPrompt: "Use scoring incentives to invite forward progression",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up","final_third"],
    designIntent: "Penetrate into final third",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as an optional consequence constraint layered onto a representative base game.",
  },
  {
    id: "tl-v0-constraint-wide-utilization-bonus",
    title: "Wide Utilization Bonus",
    description: "Reward effective use of wide areas during play",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages width",
    contextualAudit: "Avoid forcing wide play",
    suggestedConstraintPrompt: "Use scoring incentives to invite use of width",
    category: "Create Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Use width and depth",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "create_space",
    logicUsageNote: "Use as an optional consequence constraint when you want width to matter more without forcing wide play.",
  },
  {
    id: "tl-v0-constraint-switch-of-play-bonus",
    title: "Switch of Play Bonus",
    description: "Reward switching play across the field",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages scanning",
    contextualAudit: "Avoid sequence rules",
    suggestedConstraintPrompt: "Use scoring incentives to invite switching",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Switch play",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as an optional consequence constraint to increase the value of switching, not to require a sequence.",
  },
  {
    id: "tl-v0-constraint-interception-reward",
    title: "Interception Reward",
    description: "Reward defensive interceptions",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages anticipation",
    contextualAudit: "Maintain realism",
    suggestedConstraintPrompt: "Use defensive rewards to invite interceptions",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Win the ball back",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as an optional defensive consequence constraint that sharpens anticipation and regain opportunities.",
  },
  {
    id: "tl-v0-constraint-turnover-reward",
    title: "Turnover Reward",
    description: "Reward forcing turnovers from opponents",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages pressure",
    contextualAudit: "Avoid over-restriction",
    suggestedConstraintPrompt: "Use defensive rewards to invite regain",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Force turnovers",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as an optional defensive consequence constraint that increases the value of pressure and regain moments.",
  },
  {
    id: "tl-v0-constraint-delay-reward",
    title: "Delay Reward",
    description: "Reward slowing attacking progression",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages delay",
    contextualAudit: "No forced outcomes",
    suggestedConstraintPrompt: "Use defensive rewards to invite delay",
    category: "Delay or Deny",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Slow attacking progression",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "delay_or_deny",
    logicUsageNote: "Use as an optional defensive consequence constraint when slowing progression is a desired defensive outcome.",
  },
  {
    id: "tl-v0-constraint-central-density-condition",
    title: "Central Density Condition",
    description: "Increase defensive pressure in central areas",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Encourages wide play indirectly",
    contextualAudit: "Do not restrict movement",
    suggestedConstraintPrompt: "Use spatial conditions to invite decisions",
    category: "Protect Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Central pressure",
    constraintArchetype: "Spatial Condition",
    constraintRole: "structure",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "indirect_increase",
    targetAffordancePrimary: "protect_space",
    logicUsageNote: "Use as a structural/spatial constraint to shape pressure in central areas and indirectly invite width.",
  },
  {
    id: "tl-v0-constraint-wide-zone-advantage",
    title: "Wide Zone Advantage",
    description: "Provide scoring or positional advantage in wide areas",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Encourages width",
    contextualAudit: "Zones optional",
    suggestedConstraintPrompt: "Use spatial conditions to invite width",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Use wide areas",
    constraintArchetype: "Spatial Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: true,
    incentiveMechanism: "positional_or_scoring_advantage",
    visibilityEffect: "increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as a hybrid spatial + consequence constraint when wide areas should become more available and more valuable.",
  },
  {
    id: "tl-v0-constraint-final-third-value",
    title: "Final Third Value",
    description: "Increase scoring value in final third",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration",
    contextualAudit: "Maintain flexibility",
    suggestedConstraintPrompt: "Use scoring incentives to invite entry",
    category: "Break Lines",
    gameTemplateAnchor: ["final_third"],
    designIntent: "Final third entry",
    constraintArchetype: "Spatial Condition",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "value_multiplier",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as an optional consequence constraint that increases the value of penetrating into the final third.",
  },
  {
    id: "tl-v0-constraint-transition-bonus",
    title: "Transition Bonus",
    description: "Reward quick attacking actions after regain",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages transition speed",
    contextualAudit: "Avoid forcing speed",
    suggestedConstraintPrompt: "Use time-based incentives to invite fast decisions",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Exploit transitions",
    constraintArchetype: "Time Condition",
    constraintRole: "consequence",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "attack_quickly",
    logicUsageNote: "Use as an optional temporal consequence constraint that increases urgency immediately after regains.",
  },
  {
    id: "tl-v0-constraint-recovery-window",
    title: "Recovery Window",
    description: "Reward defensive recovery after transition",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages recovery",
    contextualAudit: "Maintain realism",
    suggestedConstraintPrompt: "Use time conditions to invite recovery",
    category: "Recover Shape",
    gameTemplateAnchor: ["transition"],
    designIntent: "Reorganize defense",
    constraintArchetype: "Time Condition",
    constraintRole: "consequence",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "recover_shape",
    logicUsageNote: "Use as an optional temporal consequence constraint that increases the value of fast defensive reorganization.",
  },
  {
    id: "tl-v0-constraint-transition-trigger",
    title: "Transition Trigger",
    description: "Create advantage immediately after regain",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Links phases",
    contextualAudit: "Maintain ecological validity",
    suggestedConstraintPrompt: "Use transition triggers to connect phases",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Transition play",
    constraintArchetype: "Transition Trigger",
    constraintRole: "structure",
    primaryConstraintType: "transition",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "neutral",
    targetAffordancePrimary: "attack_quickly",
    logicUsageNote: "Use as a structural transition condition that connects phases; pair with other constraints if more consequence is needed.",
  },
]
