import type { TestLibraryV0Constraint } from './types'

export const TEST_LIBRARY_V0_CONSTRAINT_POOL_ORDER = [
  "tl-v0-constraint-progression-bonus",
  "tl-v0-constraint-wide-utilization-bonus",
  "tl-v0-constraint-switch-of-play-bonus",
  "tl-v0-constraint-interception-reward",
  "tl-v0-constraint-turnover-reward",
  "tl-v0-constraint-delay-reward",
  "tl-v0-constraint-central-density-condition",
  "tl-v0-constraint-wide-zone-advantage",
  "tl-v0-constraint-final-third-value",
  "tl-v0-constraint-transition-bonus",
  "tl-v0-constraint-recovery-window",
  "tl-v0-constraint-transition-trigger",
  "tl-v0-constraint-zone-structure-condition",
  "tl-v0-constraint-neutral-player-condition",
  "tl-v0-constraint-goalkeeper-included-condition",
  "tl-v0-constraint-small-area-condition",
  "tl-v0-constraint-counter-press-window",
  "tl-v0-constraint-pass-combination-gate",
  "tl-v0-constraint-support-lane-requirement",
  "tl-v0-constraint-variable-target-condition",
  "tl-v0-constraint-multi-goal-read",
  "tl-v0-constraint-blind-side-entry",
  "tl-v0-constraint-disguised-restart"
] as const

/** Test Library V0 ? constraints (from csv/constraints.csv) */
export const TEST_LIBRARY_V0_CONSTRAINTS: TestLibraryV0Constraint[] = [
{
    id: "tl-v0-constraint-progression-bonus",
    title: "Progression Bonus",
    description: "Reward advancement into attacking areas through successful progression",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration",
    contextualAudit: "Avoid forcing direction",
    suggestedConstraintPrompt: "Use scoring incentives to invite forward progression",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up","final_third"],
    designIntent: "Penetrate into final third",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as an optional consequence constraint layered onto a representative base game.",
  },
{
    id: "tl-v0-constraint-wide-utilization-bonus",
    title: "Wide Utilization Bonus",
    description: "Reward effective use of wide areas during play",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages width",
    contextualAudit: "Avoid forcing wide play",
    suggestedConstraintPrompt: "Use scoring incentives to invite use of width",
    category: "Create Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Use width and depth",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "create_space",
    logicUsageNote: "Use as an optional consequence constraint when you want width to matter more without forcing wide play.",
  },
{
    id: "tl-v0-constraint-switch-of-play-bonus",
    title: "Switch of Play Bonus",
    description: "Reward switching play across the field",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages scanning",
    contextualAudit: "Avoid sequence rules",
    suggestedConstraintPrompt: "Use scoring incentives to invite switching",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Switch play",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as an optional consequence constraint to increase the value of switching, not to require a sequence.",
  },
{
    id: "tl-v0-constraint-interception-reward",
    title: "Interception Reward",
    description: "Reward defensive interceptions",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages anticipation",
    contextualAudit: "Maintain realism",
    suggestedConstraintPrompt: "Use defensive rewards to invite interceptions",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Win the ball back",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as an optional defensive consequence constraint that sharpens anticipation and regain opportunities.",
  },
{
    id: "tl-v0-constraint-turnover-reward",
    title: "Turnover Reward",
    description: "Reward forcing turnovers from opponents",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages pressure",
    contextualAudit: "Avoid over-restriction",
    suggestedConstraintPrompt: "Use defensive rewards to invite regain",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Force turnovers",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as an optional defensive consequence constraint that increases the value of pressure and regain moments.",
  },
{
    id: "tl-v0-constraint-delay-reward",
    title: "Delay Reward",
    description: "Reward slowing attacking progression",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages delay",
    contextualAudit: "No forced outcomes",
    suggestedConstraintPrompt: "Use defensive rewards to invite delay",
    category: "Delay or Deny",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Slow attacking progression",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "delay_or_deny",
    logicUsageNote: "Use as an optional defensive consequence constraint when slowing progression is a desired defensive outcome.",
  },
{
    id: "tl-v0-constraint-final-third-value",
    title: "Final Third Value",
    description: "Increase scoring value in final third",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration",
    contextualAudit: "Maintain flexibility",
    suggestedConstraintPrompt: "Use scoring incentives to invite entry",
    category: "Break Lines",
    gameTemplateAnchor: ["final_third"],
    designIntent: "Final third entry",
    constraintArchetype: "Spatial Condition",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "value_multiplier",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as an optional consequence constraint that increases the value of penetrating into the final third.",
  },
{
    id: "tl-v0-constraint-transition-bonus",
    title: "Transition Bonus",
    description: "Reward quick attacking actions after regain",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages transition speed",
    contextualAudit: "Avoid forcing speed",
    suggestedConstraintPrompt: "Use time-based incentives to invite fast decisions",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Exploit transitions",
    constraintArchetype: "Time Condition",
    constraintRole: "consequence",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "attack_quickly",
    logicUsageNote: "Use as an optional temporal consequence constraint that increases urgency immediately after regains.",
  },
{
    id: "tl-v0-constraint-recovery-window",
    title: "Recovery Window",
    description: "Reward defensive recovery after transition",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages recovery",
    contextualAudit: "Maintain realism",
    suggestedConstraintPrompt: "Use time conditions to invite recovery",
    category: "Recover Shape",
    gameTemplateAnchor: ["transition"],
    designIntent: "Reorganize defense",
    constraintArchetype: "Time Condition",
    constraintRole: "consequence",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "recover_shape",
    logicUsageNote: "Use as an optional temporal consequence constraint that increases the value of fast defensive reorganization.",
  },
{
    id: "tl-v0-constraint-counter-press-window",
    title: "Counter-Press Window",
    description: "A live window opens immediately after possession is lost; the pressing team attempts to regain inside that window; if the team escapes the counter-press, they earn a restart or continuation bonus.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Counter-press window creates a contested advantage moment; the team that loses possession decides whether to commit to the press immediately or protect the deeper zone; the team with the ball chooses whether to exploit the disorganized pressure or secure possession.",
    contextualAudit: "The window invites counter-pressing as a live choice — not a requirement. Teams adapt based on opponent readiness, pressure cover, and their own recovery shape.",
    suggestedConstraintPrompt: "Use the counter-press window as a scoring incentive; escaping the press earns a bonus; failing to regain inside the window means the opponent gets a live advantage and the defending team must recover shape.",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition", "build_up"],
    designIntent: "Live counter-press window creates a contested advantage on every possession change; the team losing the ball decides whether to commit to the press or recover shape; the team gaining the ball decides whether to exploit the disorganized pressure or recirculate safely.",
    constraintArchetype: "Time Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as a shaping constraint when counter-pressing intensity, transition urgency, and organized regain are central session goals.",
    setupGuidance: [
      "Coach calls out 'press' (or starts a timer) the moment possession changes.",
      "Typical counter-press window: 5 seconds. Pressing team must regain within that window for the press to count as successful.",
      "If the window expires without regain, the team in possession earns a restart bonus or free continuation.",
    ],
  },
{
    id: "tl-v0-constraint-pass-combination-gate",
    title: "Pass Combination Gate",
    description: "A goal or score attempt counts only when the team completes a connected combination of passes first; defending team can reset the count by winning possession or forcing a turnover under pressure.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Combination gate creates a visible build-up problem; teams decide when the picture is ready to commit to goal versus when recirculating and finding a better lane is the right choice; defenders choose whether to press the combination early or delay and protect space.",
    contextualAudit: "The combination is an ecological scoring gate — not a technique exercise. Teams adapt their support angles and spacing to complete combinations under live opposition.",
    suggestedConstraintPrompt: "Use the combination gate as a scoring incentive; teams choose when the picture is open to attempt goal versus when recirculation opens more space and a better option.",
    category: "Create Space",
    gameTemplateAnchor: ["build_up", "final_third"],
    designIntent: "Combination gate creates a live possession problem under opponent pressure; defending teams read the passing rhythm and choose whether to press early or delay and force the ball wide; attacking teams adapt support structure and spacing to complete combinations and unlock the score attempt.",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "hybrid",
    primaryConstraintType: "behavioral",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "create_space",
    logicUsageNote: "Use as a shaping constraint when possession circulation, support structure, and building through pressure are central session goals.",
    setupGuidance: [
      "Goal/score attempts only count when the attacking team has completed a minimum of 4-6 connected passes in their half (adjust by age/ability).",
      "Pass count resets when possession is lost or the ball leaves play.",
      "Coach tracks the count visibly (count out loud or use a counter).",
    ],
  },
  // BORDERLINE (EM vs Constraint) ? confirm with Christian's authoritative EM Library
{
    id: "tl-v0-constraint-support-lane-requirement",
    title: "Support Lane Requirement",
    description: "A penetrating pass or forward run into a scoring area counts only when a supporting player has occupied the required lane or channel; defending team reads support lane occupation and decides whether to press the ball or track the run.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Support lane creates a visible opportunity cue; attackers decide when a teammate has arrived in the lane and whether the lane is genuinely open under defensive pressure; defenders choose whether to block the lane or press the ball carrier.",
    contextualAudit: "The lane is an ecological condition — players read lane occupation and decide when to play forward based on the live picture, not on instruction.",
    suggestedConstraintPrompt: "Use support lane as a scoring gate; teams read the picture to see when the lane is occupied and live before choosing the forward pass or penetrating run.",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up", "final_third"],
    designIntent: "Support lane requirement creates a visible spatial game problem; the free player decides when to enter the lane based on defensive coverage; the ball carrier adapts timing of the forward pass based on lane occupation and pressure; defending team reacts to both the ball and the lane to deny the penetrating option.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as a shaping constraint when support runs, lane occupation, and penetrating forward passes are central to the session goal.",
    setupGuidance: [
      "Mark a support lane (typically a half-space corridor between center and wide channels) with cones.",
      "Forward passes or penetrating runs into the scoring area only count when a supporting player has entered the marked lane before the pass.",
      "The lane is a reference area — players choose when to enter and when not to, based on the live picture.",
    ],
  },
]

