import type { TestLibraryV0Constraint } from './types'

/** Test Library V0 — constraints (from csv/constraints.csv) */
export const TEST_LIBRARY_V0_CONSTRAINTS: TestLibraryV0Constraint[] = [
  {
    id: "tl-v0-constraint-progression-bonus",
    title: "Progression Bonus",
    description: "Reward advancement into attacking areas through successful progression",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration",
    contextualAudit: "Avoid forcing direction",
    suggestedConstraintPrompt: "Use scoring incentives to invite forward progression",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up","final_third"],
    designIntent: "Penetrate into final third",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as an optional consequence constraint layered onto a representative base game.",
  },
  {
    id: "tl-v0-constraint-wide-utilization-bonus",
    title: "Wide Utilization Bonus",
    description: "Reward effective use of wide areas during play",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages width",
    contextualAudit: "Avoid forcing wide play",
    suggestedConstraintPrompt: "Use scoring incentives to invite use of width",
    category: "Create Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Use width and depth",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "create_space",
    logicUsageNote: "Use as an optional consequence constraint when you want width to matter more without forcing wide play.",
  },
  {
    id: "tl-v0-constraint-switch-of-play-bonus",
    title: "Switch of Play Bonus",
    description: "Reward switching play across the field",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages scanning",
    contextualAudit: "Avoid sequence rules",
    suggestedConstraintPrompt: "Use scoring incentives to invite switching",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Switch play",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as an optional consequence constraint to increase the value of switching, not to require a sequence.",
  },
  {
    id: "tl-v0-constraint-interception-reward",
    title: "Interception Reward",
    description: "Reward defensive interceptions",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages anticipation",
    contextualAudit: "Maintain realism",
    suggestedConstraintPrompt: "Use defensive rewards to invite interceptions",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Win the ball back",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as an optional defensive consequence constraint that sharpens anticipation and regain opportunities.",
  },
  {
    id: "tl-v0-constraint-turnover-reward",
    title: "Turnover Reward",
    description: "Reward forcing turnovers from opponents",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages pressure",
    contextualAudit: "Avoid over-restriction",
    suggestedConstraintPrompt: "Use defensive rewards to invite regain",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition"],
    designIntent: "Force turnovers",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as an optional defensive consequence constraint that increases the value of pressure and regain moments.",
  },
  {
    id: "tl-v0-constraint-delay-reward",
    title: "Delay Reward",
    description: "Reward slowing attacking progression",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages delay",
    contextualAudit: "No forced outcomes",
    suggestedConstraintPrompt: "Use defensive rewards to invite delay",
    category: "Delay or Deny",
    gameTemplateAnchor: ["defensive"],
    designIntent: "Slow attacking progression",
    constraintArchetype: "Defensive Reward",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "defensive_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "delay_or_deny",
    logicUsageNote: "Use as an optional defensive consequence constraint when slowing progression is a desired defensive outcome.",
  },
  {
    id: "tl-v0-constraint-central-density-condition",
    title: "Central Density Condition",
    description: "Increase defensive pressure in central areas",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Encourages wide play indirectly",
    contextualAudit: "Do not restrict movement",
    suggestedConstraintPrompt: "Use spatial conditions to invite decisions",
    category: "Protect Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Central pressure",
    constraintArchetype: "Spatial Condition",
    constraintRole: "structure",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "indirect_increase",
    targetAffordancePrimary: "protect_space",
    logicUsageNote: "Use as a structural/spatial constraint to shape pressure in central areas and indirectly invite width.",
    setupGuidance: [
      "Mark a central zone (roughly the middle third lengthwise, half the field width) with cones or discs.",
      "Restrict defenders allowed inside the central zone (typical cap: 2-3 defenders).",
      "Outside players can enter the central zone freely; the restriction shapes defensive density without removing free movement.",
    ],
  },
  {
    id: "tl-v0-constraint-wide-zone-advantage",
    title: "Wide Zone Advantage",
    description: "Provide scoring or positional advantage in wide areas",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Encourages width",
    contextualAudit: "Zones optional",
    suggestedConstraintPrompt: "Use spatial conditions to invite width",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up"],
    designIntent: "Use wide areas",
    constraintArchetype: "Spatial Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: true,
    incentiveMechanism: "positional_or_scoring_advantage",
    visibilityEffect: "increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as a hybrid spatial + consequence constraint when wide areas should become more available and more valuable.",
    setupGuidance: [
      "Mark wide channels along both touchlines (~6-10m wide depending on field size).",
      "Actions starting in or moving through the wide channel earn an advantage (bonus point, free restart, or scoring multiplier).",
      "Channels are reference markers — players can choose to use them or not.",
    ],
  },
  {
    id: "tl-v0-constraint-final-third-value",
    title: "Final Third Value",
    description: "Increase scoring value in final third",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages penetration",
    contextualAudit: "Maintain flexibility",
    suggestedConstraintPrompt: "Use scoring incentives to invite entry",
    category: "Break Lines",
    gameTemplateAnchor: ["final_third"],
    designIntent: "Final third entry",
    constraintArchetype: "Spatial Condition",
    constraintRole: "consequence",
    primaryConstraintType: "consequence",
    includesIncentiveLayer: true,
    incentiveMechanism: "value_multiplier",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as an optional consequence constraint that increases the value of penetrating into the final third.",
  },
  {
    id: "tl-v0-constraint-transition-bonus",
    title: "Transition Bonus",
    description: "Reward quick attacking actions after regain",
    type: "constraint",
    affordanceTagGroup: "Attacking",
    notes: "Encourages transition speed",
    contextualAudit: "Avoid forcing speed",
    suggestedConstraintPrompt: "Use time-based incentives to invite fast decisions",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Exploit transitions",
    constraintArchetype: "Time Condition",
    constraintRole: "consequence",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "attack_quickly",
    logicUsageNote: "Use as an optional temporal consequence constraint that increases urgency immediately after regains.",
  },
  {
    id: "tl-v0-constraint-recovery-window",
    title: "Recovery Window",
    description: "Reward defensive recovery after transition",
    type: "constraint",
    affordanceTagGroup: "Defensive",
    notes: "Encourages recovery",
    contextualAudit: "Maintain realism",
    suggestedConstraintPrompt: "Use time conditions to invite recovery",
    category: "Recover Shape",
    gameTemplateAnchor: ["transition"],
    designIntent: "Reorganize defense",
    constraintArchetype: "Time Condition",
    constraintRole: "consequence",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "recover_shape",
    logicUsageNote: "Use as an optional temporal consequence constraint that increases the value of fast defensive reorganization.",
  },
  {
    id: "tl-v0-constraint-transition-trigger",
    title: "Transition Trigger",
    description: "Create advantage immediately after regain",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Links phases",
    contextualAudit: "Maintain ecological validity",
    suggestedConstraintPrompt: "Use transition triggers to connect phases",
    category: "Attack Quickly",
    gameTemplateAnchor: ["transition"],
    designIntent: "Transition play",
    constraintArchetype: "Transition Trigger",
    constraintRole: "structure",
    primaryConstraintType: "transition",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "neutral",
    targetAffordancePrimary: "attack_quickly",
    logicUsageNote: "Use as a structural transition condition that connects phases; pair with other constraints if more consequence is needed.",
    setupGuidance: [
      "On every possession change, play continues immediately without stoppage — no restart, no whistle.",
      "Coach calls out 'transition' or uses a visual cue at possession-change moments to focus the contest on this event.",
      "No marked zones required for the trigger itself; whatever zones exist for other constraints stay live through the transition.",
    ],
  },
  // ─── Foundation constraints (role: structure) ────────────────────────────────
  {
    id: "tl-v0-constraint-zone-structure-condition",
    title: "Zone Structure Condition",
    description: "Field divided into defined zones; teams progress through zone transitions under live opposition; spatial awareness and zone occupation shape attacking and defending decisions.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Zone boundaries create visible reference points for pressure reads; players decide when the picture is open to progress into the next zone, support from depth, or switch the attack across zones.",
    contextualAudit: "Zones shape the environment — they do not restrict how players choose to act within or between zones.",
    suggestedConstraintPrompt: "Use zone structure to invite spatial decision-making; players read zone occupation and pressure before choosing the next action.",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up", "final_third", "transition"],
    designIntent: "Spatial zone structure forces teams to progress through defined areas under opposition; teams adapt routes based on which zones are open or crowded under pressure.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "structure",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "indirect_increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as a structural foundation constraint when spatial awareness, zone transitions, and directional progression are central to the session goal.",
    setupGuidance: [
      "Divide the field into 3-4 defined zones (e.g., build-up / mid / attacking; or left / center / right channels).",
      "Mark zone boundaries clearly with cones or discs.",
      "Players move freely between zones; the structure exists to make zone transitions visible, not to limit movement.",
    ],
  },
  {
    id: "tl-v0-constraint-neutral-player-condition",
    title: "Neutral Player Condition",
    description: "One or more neutral players join the team in possession creating a live numerical overload; defending team reads the support angles and decides whether to press the free player or protect the deeper zone.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Neutral player changes the space, support angles, and passing options for both sides; attackers decide whether to use the overload immediately or recirculate to find a better lane.",
    contextualAudit: "Neutral player creates structural overload — not a coaching script. Players choose when and how to use the numerical advantage based on the live pressure picture.",
    suggestedConstraintPrompt: "Use neutral player structure to invite overload exploitation; defenders decide how to cover the extra option while attackers choose the best moment to use the numerical advantage.",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up", "transition", "final_third"],
    designIntent: "Numerical advantage from the neutral player creates visible pressure differences and support options; teams read the picture to decide when the free option opens space or invites the penetrating pass.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "structure",
    primaryConstraintType: "structural",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "indirect_increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as a structural foundation constraint when overload exploitation, support angles, and numerical advantage in possession are central to the session goal.",
    setupGuidance: [
      "Designate one or two neutral players (wear contrasting bibs).",
      "Neutrals always play with the team in possession, creating a permanent numerical advantage for whichever side has the ball.",
      "Adjust team numbers accordingly (e.g., for 15 players: 6v6 + 3 neutrals, or 7v7 + 1 neutral).",
    ],
  },
  {
    id: "tl-v0-constraint-goalkeeper-included-condition",
    title: "Goalkeeper Included Condition",
    description: "Goalkeeper is active in all phases as a live option for distribution, support, and recovery; attacking team reads the space behind defensive lines and decides when to pressure the target area under live goal threat.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "GK inclusion adds a live pressure reference on both sides; attackers read the goalkeeper position and support angles to choose finishing windows; defenders use GK as a support option to escape pressure.",
    contextualAudit: "GK participation is structural — players choose when and how to involve the GK as they would in a real match, not on instruction.",
    suggestedConstraintPrompt: "Use goalkeeper inclusion to invite realistic build-up and finishing pressure; teams read GK positioning and space behind the last line before deciding to attack or recirculate.",
    category: "Break Lines",
    gameTemplateAnchor: ["final_third", "build_up"],
    designIntent: "Live goalkeeper creates a real target and real pressure on attacking and defending decisions; space behind the defensive line, support angles, and finishing windows are all live based on GK position and defensive recovery.",
    constraintArchetype: "Structural Condition",
    constraintRole: "structure",
    primaryConstraintType: "structural",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as a structural foundation constraint when finishing under pressure, build-up from back, and live goalkeeper pressure are central to the session goal.",
    setupGuidance: [
      "Goalkeepers in their normal goal positions at each end of the field.",
      "GKs are live during all phases — they distribute, save, and count as outfield support when team is building from the back.",
      "Use full-size or scaled goals depending on field dimensions.",
    ],
  },
  {
    id: "tl-v0-constraint-small-area-condition",
    title: "Small Area Condition",
    description: "Compact pitch proportions place teams in tight space with reduced time; all attacking and defending actions occur under live pressure within a smaller area; spatial awareness and timing shape every decision.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Reduced space intensifies pressure cycles; teams read opponent pressure and support angles in a tighter window before choosing to secure possession, switch play, or escape into space.",
    contextualAudit: "Space reduction is structural — it creates representative pressure through environment, not scripted actions.",
    suggestedConstraintPrompt: "Use small area structure to sharpen decision-making under pressure; players read pressure and support in tight zones before choosing the next action.",
    category: "Protect Space",
    gameTemplateAnchor: ["build_up", "transition", "final_third"],
    designIntent: "Compact area forces faster reads and tighter support decisions; space is at a premium and teams adapt their timing, passing angles, and movement based on the live pressure picture.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "structure",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "indirect_increase",
    targetAffordancePrimary: "protect_space",
    logicUsageNote: "Use as a structural foundation constraint when spatial compactness, pressure under reduced time, and tight decision-making are central to the session goal.",
    setupGuidance: [
      "Reduce the field to a compact area (typical: 30-40m x 25-35m for 8-12 players).",
      "Tight boundaries increase pressure cycles without changing the basic game form.",
      "Adjust dimensions based on player age and ability — smaller for tighter pressure, larger to ease cognitive load.",
    ],
  },
  // ─── Shaping constraints (role: hybrid) ──────────────────────────────────────
  {
    id: "tl-v0-constraint-counter-press-window",
    title: "Counter-Press Window",
    description: "A live window opens immediately after possession is lost; the pressing team attempts to regain inside that window; if the team escapes the counter-press, they earn a restart or continuation bonus.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Counter-press window creates a contested advantage moment; the team that loses possession decides whether to commit to the press immediately or protect the deeper zone; the team with the ball chooses whether to exploit the disorganized pressure or secure possession.",
    contextualAudit: "The window invites counter-pressing as a live choice — not a requirement. Teams adapt based on opponent readiness, pressure cover, and their own recovery shape.",
    suggestedConstraintPrompt: "Use the counter-press window as a scoring incentive; escaping the press earns a bonus; failing to regain inside the window means the opponent gets a live advantage and the defending team must recover shape.",
    category: "Regain Possession",
    gameTemplateAnchor: ["transition", "build_up"],
    designIntent: "Live counter-press window creates a contested advantage on every possession change; the team losing the ball decides whether to commit to the press or recover shape; the team gaining the ball decides whether to exploit the disorganized pressure or recirculate safely.",
    constraintArchetype: "Time Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "temporal",
    includesIncentiveLayer: true,
    incentiveMechanism: "time_window_reward",
    visibilityEffect: "increase",
    targetAffordancePrimary: "regain_possession",
    logicUsageNote: "Use as a shaping constraint when counter-pressing intensity, transition urgency, and organized regain are central session goals.",
    setupGuidance: [
      "Coach calls out 'press' (or starts a timer) the moment possession changes.",
      "Typical counter-press window: 5 seconds. Pressing team must regain within that window for the press to count as successful.",
      "If the window expires without regain, the team in possession earns a restart bonus or free continuation.",
    ],
  },
  {
    id: "tl-v0-constraint-pass-combination-gate",
    title: "Pass Combination Gate",
    description: "A goal or score attempt counts only when the team completes a connected combination of passes first; defending team can reset the count by winning possession or forcing a turnover under pressure.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Combination gate creates a visible build-up problem; teams decide when the picture is ready to commit to goal versus when recirculating and finding a better lane is the right choice; defenders choose whether to press the combination early or delay and protect space.",
    contextualAudit: "The combination is an ecological scoring gate — not a technique exercise. Teams adapt their support angles and spacing to complete combinations under live opposition.",
    suggestedConstraintPrompt: "Use the combination gate as a scoring incentive; teams choose when the picture is open to attempt goal versus when recirculation opens more space and a better option.",
    category: "Create Space",
    gameTemplateAnchor: ["build_up", "final_third"],
    designIntent: "Combination gate creates a live possession problem under opponent pressure; defending teams read the passing rhythm and choose whether to press early or delay and force the ball wide; attacking teams adapt support structure and spacing to complete combinations and unlock the score attempt.",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "hybrid",
    primaryConstraintType: "behavioral",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "create_space",
    logicUsageNote: "Use as a shaping constraint when possession circulation, support structure, and building through pressure are central session goals.",
    setupGuidance: [
      "Goal/score attempts only count when the attacking team has completed a minimum of 4-6 connected passes in their half (adjust by age/ability).",
      "Pass count resets when possession is lost or the ball leaves play.",
      "Coach tracks the count visibly (count out loud or use a counter).",
    ],
  },
  {
    id: "tl-v0-constraint-support-lane-requirement",
    title: "Support Lane Requirement",
    description: "A penetrating pass or forward run into a scoring area counts only when a supporting player has occupied the required lane or channel; defending team reads support lane occupation and decides whether to press the ball or track the run.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Support lane creates a visible opportunity cue; attackers decide when a teammate has arrived in the lane and whether the lane is genuinely open under defensive pressure; defenders choose whether to block the lane or press the ball carrier.",
    contextualAudit: "The lane is an ecological condition — players read lane occupation and decide when to play forward based on the live picture, not on instruction.",
    suggestedConstraintPrompt: "Use support lane as a scoring gate; teams read the picture to see when the lane is occupied and live before choosing the forward pass or penetrating run.",
    category: "Break Lines",
    gameTemplateAnchor: ["build_up", "final_third"],
    designIntent: "Support lane requirement creates a visible spatial game problem; the free player decides when to enter the lane based on defensive coverage; the ball carrier adapts timing of the forward pass based on lane occupation and pressure; defending team reacts to both the ball and the lane to deny the penetrating option.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "spatial",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "increase",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as a shaping constraint when support runs, lane occupation, and penetrating forward passes are central to the session goal.",
    setupGuidance: [
      "Mark a support lane (typically a half-space corridor between center and wide channels) with cones.",
      "Forward passes or penetrating runs into the scoring area only count when a supporting player has entered the marked lane before the pass.",
      "The lane is a reference area — players choose when to enter and when not to, based on the live picture.",
    ],
  },
  // ─── Information-shaping constraints (Round 8C) ───────────────────────────────
  // These shape the INFORMATION landscape — what is available, hidden, delayed, uncertain, or out of
  // view — rather than rewarding an observable behavior. Scanning, anticipation, and recognition are
  // expected to EMERGE as adaptations; they are not rewarded directly (that belongs to the Observation
  // layer, per Christian's Round-8C distinction). Pre-Scan Requirement was considered and rejected for
  // exactly that reason — it would grade the scan itself rather than shape what is perceivable.
  {
    id: "tl-v0-constraint-variable-target-condition",
    title: "Variable Target Condition",
    description: "Which target or scoring option is live is revealed late or changes during play, so teams must read the current picture rather than commit to a pre-planned route.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Players cannot lock onto a pre-chosen target; they keep options open and perceive which target has become live under pressure. Scanning emerges as one adaptation, it is not required.",
    contextualAudit: "The variability shapes information availability, not behavior — players choose how to exploit whichever target is live.",
    suggestedConstraintPrompt: "Use a late or changing live-target rule so teams read the current picture before committing to a route.",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up", "final_third", "transition"],
    designIntent: "Delaying or varying which target is live forces perception of the live picture over pre-planned routes; teams adapt the direction of their progression to the target that becomes available.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "hybrid",
    primaryConstraintType: "information",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "decrease",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as a shaping information constraint when reading the live picture and adapting the target of progression are central to the session goal.",
    coachVocabulary: [
      "read the picture", "which option is on", "late target", "variable target",
      "don't pre-plan", "keep options open", "read before committing", "play what you see",
      "the open target changes", "perceive the live option",
    ],
    setupGuidance: [
      "Mark 2-3 possible targets/gates (e.g. across the far line or at multiple edges).",
      "Which target is live is revealed only after play crosses a trigger line, or switches on a coach cue during play.",
      "All targets stay physically available so the choice remains open; only the LIVE one scores.",
    ],
  },
  {
    id: "tl-v0-constraint-multi-goal-read",
    title: "Multi-Goal Read",
    description: "Two or more goals/targets are live at once and defended differently; the attack must perceive which is least protected at this moment rather than attack a single known target.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Multiple simultaneous targets distribute the information across the field; players read which target the defense has left open and the defense shifts to cover, so the open option keeps moving.",
    contextualAudit: "The multiple targets shape what must be perceived — players choose which to attack; no specific target or movement is prescribed.",
    suggestedConstraintPrompt: "Use multiple simultaneously-live goals so the attack perceives which is open rather than attacking one fixed target.",
    category: "Exploit Space",
    gameTemplateAnchor: ["build_up", "final_third"],
    designIntent: "Several live targets create a perception problem: the attack reads which target is least protected now and the defense reorganizes to cover, so advantage comes from recognizing the open option, not from a rehearsed route.",
    constraintArchetype: "Spatial Condition",
    constraintRole: "structure",
    primaryConstraintType: "information",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "increase",
    targetAffordancePrimary: "exploit_space",
    logicUsageNote: "Use as a structural information constraint when perceiving and attacking the open option among several is central to the session goal.",
    coachVocabulary: [
      "two goals", "multiple goals", "multiple targets", "which goal is open",
      "attack the open goal", "read which is open", "find the unguarded target",
      "scan the targets", "perceive the open option", "switch target",
    ],
    setupGuidance: [
      "Set 2-3 small goals/targets spread across the end line (or at multiple edges of the field).",
      "All targets are live to score at the same time; defenders cannot cover all equally.",
      "Field width keeps the targets far enough apart that the attack must perceive and exploit which is open.",
    ],
  },
  {
    id: "tl-v0-constraint-blind-side-entry",
    title: "Blind-Side Entry",
    description: "Advantage created from outside a defender's field of view (a run or pass arriving from the blind side) is worth more, rewarding the relationship rather than any specific movement.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "Players read where defenders are not looking and exploit the blind side; defenders adapt their body orientation and scanning. The reward is for the perceptual relationship, not a prescribed run.",
    contextualAudit: "Rewards the OUTCOME of using a blind-side relationship — there are many ways to create one — never a specific movement pattern.",
    suggestedConstraintPrompt: "Reward advantage gained from a defender's blind side so players read body orientation and exploit where defenders cannot see.",
    category: "Break Lines",
    gameTemplateAnchor: ["final_third", "build_up"],
    designIntent: "Information out of a defender's view is the resource: advantage created from the blind side counts more, so players perceive defender orientation and exploit unseen space — many movements satisfy it.",
    constraintArchetype: "Scoring Incentive",
    constraintRole: "consequence",
    primaryConstraintType: "information",
    includesIncentiveLayer: true,
    incentiveMechanism: "scoring_bonus",
    visibilityEffect: "decrease",
    targetAffordancePrimary: "break_lines",
    logicUsageNote: "Use as a consequence information constraint when perceiving and exploiting a defender's blind side is central to the session goal; keep the reward tied to the relationship, not a set run.",
    coachVocabulary: [
      "blind side", "blind-side run", "behind the defender", "where they aren't looking",
      "out of view", "back-post run", "unseen run", "exploit the blind side",
      "defender's shoulder", "arrive unseen",
    ],
    setupGuidance: [
      "Play toward a real goal/target with active defenders and (ideally) a goalkeeper.",
      "Advantage or a goal created from a blind-side relationship (a run or pass arriving from outside the defender's view) is worth more (e.g. counts double).",
      "Do not specify the run — any action that exploits a defender's blind side qualifies.",
    ],
  },
  {
    id: "tl-v0-constraint-disguised-restart",
    title: "Disguised Restart",
    description: "Each repetition restarts from a variable, not-pre-known entry, so neither team can rehearse a picture; both must read and organize live. Scoped to variable-entry pictures, not reaction or signal-guessing tasks.",
    type: "constraint",
    affordanceTagGroup: "Both",
    notes: "The entry point/side is chosen at the last moment, so the starting picture differs each rep; teams perceive and organize to the live situation instead of running a rehearsed pattern.",
    contextualAudit: "Shapes information by removing a pre-set picture — it must NOT become a coach-signal-guessing or reaction-time task. The variability is in the entry, not a behavior cue.",
    suggestedConstraintPrompt: "Restart from a variable, last-moment entry so neither team can pre-arrange a picture and both must read the live situation.",
    category: "Create Space",
    gameTemplateAnchor: ["build_up", "transition"],
    designIntent: "A variable entry removes the pre-set picture each repetition; teams cannot rehearse, so they perceive and organize to whatever situation the restart presents — mirroring how real restarts and transitions arrive unpredictably.",
    constraintArchetype: "Structural Condition",
    constraintRole: "structure",
    primaryConstraintType: "information",
    includesIncentiveLayer: false,
    incentiveMechanism: "none",
    visibilityEffect: "decrease",
    targetAffordancePrimary: "create_space",
    logicUsageNote: "Use as a structural information constraint when reading and organizing to an unrehearsed starting picture is central to the session goal; keep it to variable entries, not reaction tasks.",
    coachVocabulary: [
      "variable restart", "different starting picture", "can't rehearse", "read the restart",
      "unpredictable entry", "organize live", "fresh picture each time", "varied entry point",
      "restart from a different side", "no set start",
    ],
    setupGuidance: [
      "Prepare several possible entry points/gates around the field (e.g. 3-4 served-in locations).",
      "Which entry is used is chosen at the last moment, so neither team knows the starting picture in advance.",
      "Keep play continuous once the ball enters; the variability is only in WHERE/HOW it starts, never a behavior the coach calls.",
    ],
  },
]
