import type { TestLibraryV0LoadReport } from './types'

/**
 * Auto-generated by generate-data-from-csv.mjs — do not edit by hand.
 * Regenerate: node src/system/test-library/generate-data-from-csv.mjs
 */
export const TEST_LIBRARY_V0_LOAD_REPORT: TestLibraryV0LoadReport = {
  "generatedAtIso": "2026-05-03T14:05:30.041Z",
  "sourceCsvRelativeDir": "src/system/test-library/csv",
  "counts": {
    "totalArchetypesLoaded": 10,
    "totalAffordanceLensesLoaded": 10,
    "totalConstraintsLoaded": 12
  },
  "csvStats": {
    "affordanceLenses": {
      "dataRowsAttempted": 10,
      "dataRowsAccepted": 10
    },
    "constraints": {
      "dataRowsAttempted": 12,
      "dataRowsAccepted": 12
    },
    "archetypes": {
      "dataRowsAttempted": 10,
      "dataRowsAccepted": 10
    }
  },
  "skippedRows": [],
  "validationErrors": []
}
