/**
 * Soccer Sport Module loader — RC1 Candidate v3.
 *
 * Canonical source: the workbook committed verbatim at
 * `back/data/sport-modules/soccer/soccer-module.rc1-v3.xlsx`, projected completely into
 * `soccer-module.rc1-v3.json` (generated by `project-workbook.py` — never hand-edit).
 *
 * WHY THIS IS NOT UNDER knowledge-core/. That directory holds Christian's canonical *universal*
 * knowledge libraries, which are sport-neutral by construction. A Sport Module is a different kind
 * of thing: it is the detachable layer that maps soccer onto those universal concepts. Keeping them
 * apart is the point of the whole exercise, so the directory boundary reflects it.
 *
 * EXTRACTION STATUS — ALL SIX SHEETS POPULATED. Game Forms (11), Realizations (23), Lenses (10),
 * Realization Banks (13), Vocabulary (175) and Coverage (17). The integrity gate checks each sheet
 * against the workbook's own declared expected-row count, so a truncated sheet is a named failure.
 *
 * TWO SHEETS ARE POPULATED BUT NOT YET AUTHORITATIVE. Vocabulary mirrors the legacy regex parser,
 * which remains the runtime router; Coverage is derived from the engine rather than driving it.
 * Both are proven against the live engine on every test run, so they cannot drift silently — but
 * repointing routing at Vocabulary is a separate governed step, for the same reason the registry
 * seeding was: while data and wiring move together, a routing change cannot be attributed to either.
 *
 * WIRED TO SELECTION as of 2026-08-05. `registry.ts` is seeded from `soccer-module-adapter`, so the
 * selector reads soccer knowledge from this workbook rather than from the in-code arrays. The arrays
 * survive only as the equivalence reference the adapter test compares against; deleting them is a
 * separate deliberate step.
 *
 * The wiring was held back until the last field had a home, for a reason worth keeping: while any
 * field was unmapped, a behaviour change could not be attributed. It could be lost data or new
 * knowledge, and untangling the two after the fact is far more expensive than waiting.
 */
import workbook from './soccer-module.rc1-v3.json'

export type SoccerModuleRow = Record<string, string | number | null>

interface SoccerModuleWorkbook {
    metadata: Record<string, string | number | null>
    vocabulary: SoccerModuleRow[]
    lenses: SoccerModuleRow[]
    game_forms: SoccerModuleRow[]
    realizations: SoccerModuleRow[]
    realization_banks: SoccerModuleRow[]
    coverage: SoccerModuleRow[]
}

const WB = workbook as unknown as SoccerModuleWorkbook

/** Sheets the integrity gate checks, paired with their metadata count key. */
const COUNTED_SHEETS = [
    ['vocabulary', 'vocabulary_expected_rows'],
    ['lenses', 'lenses_expected_rows'],
    ['game_forms', 'game_forms_expected_rows'],
    ['realizations', 'realizations_expected_rows'],
    ['realization_banks', 'realization_banks_expected_rows'],
    ['coverage', 'coverage_expected_rows'],
] as const

export interface SoccerModuleIntegrityResult {
    valid: boolean
    errors: string[]
}

/** The five data sheets, with the exact sheet name the projection expects to find. */
const DECLARED_SHEETS = [
    ['vocabulary', 'Vocabulary'],
    ['lenses', 'Lenses'],
    ['game_forms', 'Game Forms'],
    ['realizations', 'Realizations'],
    ['realization_banks', 'Realization Banks'],
    ['coverage', 'Coverage'],
] as const

/**
 * Metadata shape check — the guard against a round-tripped workbook.
 *
 * The workbook is edited on shared Drive. If it is converted to a Google Sheet and exported back,
 * typed values and sheet names can change without anyone touching a cell. The dangerous part is that
 * most of those changes do not error: a renamed sheet or a lost `*_header_row` key makes the
 * projection read the wrong row and produce an EMPTY sheet, which then looks like "the knowledge
 * hasn't been populated yet" rather than "the file arrived damaged".
 *
 * So this checks the declarations themselves rather than the data, and says *conversion* out loud in
 * the message — because the person reading the failure will otherwise go looking in the wrong place.
 */
export function validateModuleMetadataShape(data: SoccerModuleWorkbook = WB): string[] {
    const errors: string[] = []
    const meta = data.metadata
    const conversionHint = 'This usually means the workbook was converted to another format and exported back.'

    for (const [key, expectedSheetName] of DECLARED_SHEETS) {
        const nameKey = `${key}_sheet_name`
        const headerKey = `${key}_header_row`

        const declaredName = meta[nameKey]
        if (declaredName === undefined || declaredName === null) {
            errors.push(`Metadata is missing ${nameKey}. ${conversionHint}`)
        } else if (String(declaredName) !== expectedSheetName) {
            errors.push(
                `${nameKey}="${String(declaredName)}" but the projection expects the sheet named "${expectedSheetName}". ` +
                    `A renamed sheet makes every row read empty rather than failing. ${conversionHint}`
            )
        }

        // The projection DEFAULTS this to 2 when absent, so a lost key silently misreads the sheet
        // instead of erroring. Requiring it explicitly is what turns that into a named failure.
        const headerRow = meta[headerKey]
        if (headerRow === undefined || headerRow === null || !Number.isFinite(Number(headerRow))) {
            errors.push(
                `Metadata ${headerKey} is missing or non-numeric (got ${JSON.stringify(headerRow)}). ` +
                    `The projection would fall back to row 2 and could read the wrong header. ${conversionHint}`
            )
        }
    }

    // Version pins. A workbook that lost these is not identifiable, and a module whose provenance
    // cannot be established should not load quietly.
    for (const key of ['module_id', 'workbook_schema_version', 'runtime_interface_version']) {
        if (meta[key] === undefined || meta[key] === null || String(meta[key]).trim() === '') {
            errors.push(`Metadata is missing ${key}; the module cannot be identified or version-checked.`)
        }
    }

    return errors
}

/**
 * Load-time integrity gate, validated against the workbook's OWN declarations rather than against
 * numbers written here. The same principle as the six canonical libraries: if the workbook and the
 * projection disagree, that is a defined failure, never a silent one.
 */
export function validateSoccerModuleIntegrity(data: SoccerModuleWorkbook = WB): SoccerModuleIntegrityResult {
    // Shape first: if the declarations are damaged, the row counts below are meaningless — an empty
    // sheet would agree with an expected count of zero and the module would load looking fine.
    const errors: string[] = [...validateModuleMetadataShape(data)]
    const meta = data.metadata

    for (const [sheet, countKey] of COUNTED_SHEETS) {
        const declared = Number(meta[countKey])
        if (!Number.isFinite(declared)) {
            errors.push(`Metadata is missing ${countKey}; the loader cannot verify the ${sheet} sheet.`)
            continue
        }
        const actual = data[sheet].length
        if (declared !== actual) {
            errors.push(`${countKey}=${declared} but the projection holds ${actual} ${sheet} rows.`)
        }
    }

    if (String(meta['one_table_per_sheet'] ?? '').toUpperCase() !== 'TRUE') {
        errors.push('one_table_per_sheet must be TRUE — the projection assumes a single table per sheet.')
    }

    // Every populated row needs a stable identifier, or nothing downstream can reference it.
    const idColumns: Array<[keyof SoccerModuleWorkbook, string]> = [
        ['game_forms', 'game_form_id'],
        ['vocabulary', 'vocabulary_id'],
        ['lenses', 'lens_id'],
        ['realizations', 'realization_id'],
        ['realization_banks', 'realization_bank_entry_id'],
        ['coverage', 'coverage_id'],
    ]
    for (const [sheet, idColumn] of idColumns) {
        const seen = new Set<string>()
        for (const row of data[sheet] as SoccerModuleRow[]) {
            const id = row[idColumn]
            if (id === null || id === undefined || String(id).trim() === '') {
                errors.push(`A ${sheet} row is missing ${idColumn}.`)
                continue
            }
            const key = String(id)
            if (seen.has(key)) errors.push(`Duplicate ${idColumn} "${key}" in ${sheet}.`)
            seen.add(key)
        }
    }

    errors.push(...validateRealizationBanks(data))
    errors.push(...validateVocabulary(data))

    return { valid: errors.length === 0, errors }
}

/**
 * Vocabulary integrity.
 *
 * Vocabulary is the sheet Christian will edit most — it is the reason the sheet exists — so the gate
 * has to protect an EDITOR, not just an extraction. The failures that matter are the ones that look
 * harmless in a spreadsheet: a phrase with no signal group routes nowhere, a blank phrase matches
 * everything or nothing depending on the matcher, and an EXCLUDE row with no disambiguation rule is
 * an override whose reason has been lost.
 *
 * Deliberately NOT checked: whether a phrase actually routes to its group at runtime. That is proven
 * at extraction time against the live parser, and re-proving it here would mean the loader running
 * the parser on every boot. The check belongs in the test, and it is there.
 */
export function validateVocabulary(data: SoccerModuleWorkbook = WB): string[] {
    const errors: string[] = []

    for (const row of data.vocabulary) {
        const id = String(row['vocabulary_id'] ?? '(no id)')
        if (String(row['phrase'] ?? '').trim() === '') {
            errors.push(`Vocabulary row "${id}" has no phrase.`)
        }
        if (String(row['signal_group_id'] ?? '').trim() === '') {
            errors.push(`Vocabulary row "${id}" has no signal_group_id, so it routes nowhere.`)
        }

        const polarity = String(row['routing_polarity'] ?? '').trim().toUpperCase()
        if (polarity && !['INCLUDE', 'EXCLUDE'].includes(polarity)) {
            errors.push(`Vocabulary row "${id}" has routing_polarity "${polarity}"; expected INCLUDE or EXCLUDE.`)
        }
        if (polarity === 'EXCLUDE' && String(row['disambiguation_rule'] ?? '').trim() === '') {
            errors.push(
                `Vocabulary row "${id}" is an EXCLUDE rule with no disambiguation_rule. An override whose ` +
                    `reason is not written down is the kind nobody dares remove later.`
            )
        }
    }

    return errors
}

/**
 * Realization Banks integrity — the checks a normalized child resource needs and a flat column did not.
 *
 * ORDER IS BEHAVIOUR HERE. `build-activity-skeleton.ts` designates the spine for a given design with
 * `bank[(variationIndex + i) % bank.length]`. So an entry's ordinal is not decoration: it decides
 * which realization a repeat design gets built around. Three ways that breaks silently, all checked:
 *
 *   * a GAP (1, 2, 4) — the sheet still loads, but the author's third entry is now in slot three of
 *     a three-long bank, so the rotation lands somewhere nobody chose;
 *   * a DUPLICATE ordinal — two entries claim one slot and which wins depends on row order;
 *   * a DANGLING bank — entries whose `realization_id` matches no realization are simply never read,
 *     which looks identical to "we haven't authored that one yet".
 *
 * None of these move a score. They change the text of generated activities, which is exactly the
 * class of failure the delimiter incident taught us to gate at load time rather than discover later.
 */
export function validateRealizationBanks(data: SoccerModuleWorkbook = WB): string[] {
    const errors: string[] = []
    const realizationIds = new Set(data.realizations.map((r) => String(r['realization_id'] ?? '').trim()))

    const byBank = new Map<string, SoccerModuleRow[]>()
    for (const row of data.realization_banks) {
        const bankId = String(row['realization_bank_id'] ?? '').trim()
        const entryId = String(row['realization_bank_entry_id'] ?? '').trim()
        if (!bankId) {
            errors.push(`Realization bank entry "${entryId}" has no realization_bank_id.`)
            continue
        }

        const ownerId = String(row['realization_id'] ?? '').trim()
        if (!realizationIds.has(ownerId)) {
            errors.push(
                `Realization bank entry "${entryId}" references realization "${ownerId}", which is not on the ` +
                    `Realizations sheet. Its entries would never be read — an unreachable bank looks exactly ` +
                    `like an unauthored one.`
            )
        }
        if (String(row['realization_text'] ?? '').trim() === '') {
            errors.push(`Realization bank entry "${entryId}" has no realization_text; an empty spine cannot be designated.`)
        }

        const entries = byBank.get(bankId) ?? []
        entries.push(row)
        byBank.set(bankId, entries)
    }

    for (const [bankId, entries] of byBank) {
        const ordinals = entries.map((e) => Number(e['bank_ordinal']))
        if (ordinals.some((o) => !Number.isInteger(o) || o < 1)) {
            errors.push(`Bank "${bankId}" has a non-integer or non-positive bank_ordinal; ordinals must be 1-based.`)
            continue
        }
        const sorted = [...ordinals].sort((a, b) => a - b)
        const expected = sorted.map((_, i) => i + 1)
        if (sorted.join(',') !== expected.join(',')) {
            errors.push(
                `Bank "${bankId}" ordinals are [${sorted.join(', ')}] but must be contiguous 1..${entries.length}. ` +
                    `A gap or duplicate shifts which realization each variation designates.`
            )
        }
    }

    // The other direction: a realization pointing at a bank that holds nothing. The FK reads as
    // "this has alternatives" while assembly silently falls back to setup guidance.
    for (const realization of data.realizations) {
        const bankId = String(realization['realization_bank_id'] ?? '').trim()
        if (bankId && !byBank.has(bankId)) {
            errors.push(
                `Realization "${String(realization['realization_id'])}" declares realization_bank_id "${bankId}", ` +
                    `but that bank has no entries.`
            )
        }
    }

    return errors
}

/**
 * Universal identifiers the module cannot yet supply, reported rather than invented.
 *
 * Extraction surfaced these immediately: our game forms predate the canonical Game Archetype
 * Library and were never bridged to it, and routing goes through signal groups rather than GP-IDs.
 * Both need a decision from the knowledge side; guessing at them inside a loader would bury a
 * coaching judgement in code where nobody would ever find it.
 */
export function reportUnmappedUniversalIds(data: SoccerModuleWorkbook = WB): Record<string, number> {
    const missing = (rows: SoccerModuleRow[], column: string) =>
        rows.filter((r) => r[column] === null || r[column] === undefined || String(r[column]).trim() === '').length

    return {
        'game_forms.canonical_game_archetype_id': missing(data.game_forms, 'canonical_game_archetype_id'),
        'game_forms.primary_game_problem_ids': missing(data.game_forms, 'primary_game_problem_ids'),
    }
}

export const soccerModule = {
    metadata: WB.metadata,
    moduleId: String(WB.metadata['module_id'] ?? 'sport.soccer'),
    version: String(WB.metadata['workbook_schema_version'] ?? 'RC1-CANDIDATE-V3'),
    runtimeInterfaceVersion: String(WB.metadata['runtime_interface_version'] ?? ''),
    vocabulary: () => WB.vocabulary,
    /** Vocabulary rows for one signal group, in the parser's own evaluation order. */
    vocabularyForSignalGroup: (signalGroupId: string) =>
        WB.vocabulary
            .filter((r) => String(r['signal_group_id'] ?? '') === signalGroupId)
            .sort((a, b) => Number(a['fallback_priority'] ?? 0) - Number(b['fallback_priority'] ?? 0)),
    /** Coverage row for a canonical Game Problem — the basis for an honest unsupported-goal answer. */
    coverageForGameProblem: (gameProblemId: string) =>
        WB.coverage.find((r) => String(r['game_problem_id'] ?? '') === gameProblemId),
    lenses: () => WB.lenses,
    gameForms: () => WB.game_forms,
    realizations: () => WB.realizations,
    realizationBanks: () => WB.realization_banks,
    coverage: () => WB.coverage,
    gameForm: (id: string) => WB.game_forms.find((r) => String(r['game_form_id']) === id),
    realization: (id: string) => WB.realizations.find((r) => String(r['realization_id']) === id),
    /**
     * A bank's entries in ORDINAL order, not sheet order. Callers get the alternatives as text, since
     * the ordinal's only job is to establish this sequence — once sorted it has nothing left to say.
     * Returns `[]` for an absent or empty bank, matching "this realization has no alternatives".
     */
    realizationBank: (bankId: string): string[] =>
        WB.realization_banks
            .filter((r) => String(r['realization_bank_id'] ?? '').trim() === bankId)
            .sort((a, b) => Number(a['bank_ordinal']) - Number(b['bank_ordinal']))
            .map((r) => String(r['realization_text'] ?? '')),
}
