/**
 * Soccer Sport Module loader — RC1 Candidate v3.
 *
 * Canonical source: the workbook committed verbatim at
 * `back/data/sport-modules/soccer/soccer-module.rc1-v3.xlsx`, projected completely into
 * `soccer-module.rc1-v3.json` (generated by `project-workbook.py` — never hand-edit).
 *
 * WHY THIS IS NOT UNDER knowledge-core/. That directory holds Christian's canonical *universal*
 * knowledge libraries, which are sport-neutral by construction. A Sport Module is a different kind
 * of thing: it is the detachable layer that maps soccer onto those universal concepts. Keeping them
 * apart is the point of the whole exercise, so the directory boundary reflects it.
 *
 * EXTRACTION STATUS. Game Forms are populated (11 rows, extracted from `TEST_LIBRARY_V0_ARCHETYPES`)
 * and Realizations are populated (23 rows, extracted from Test Library V0 constraints and
 * environmental manipulations). Vocabulary, Lenses and Coverage are empty pending later slices. The
 * integrity gate checks each sheet against the workbook's own declared expected-row count, so a
 * partially populated module is a legitimate, verifiable state rather than an ambiguous one.
 *
 * NOT WIRED TO SELECTION. Nothing reads this at runtime yet — `generateSelection` still uses the
 * in-code libraries. That is deliberate: this slice proves the module loads and validates, and
 * repointing selection at it is where the behaviour gate is actually at risk. Doing both at once
 * would make a gate failure ambiguous between "extraction lost data" and "wiring is wrong".
 */
import workbook from './soccer-module.rc1-v3.json'

export type SoccerModuleRow = Record<string, string | number | null>

interface SoccerModuleWorkbook {
    metadata: Record<string, string | number | null>
    vocabulary: SoccerModuleRow[]
    lenses: SoccerModuleRow[]
    game_forms: SoccerModuleRow[]
    realizations: SoccerModuleRow[]
    coverage: SoccerModuleRow[]
}

const WB = workbook as unknown as SoccerModuleWorkbook

/** Sheets the integrity gate checks, paired with their metadata count key. */
const COUNTED_SHEETS = [
    ['vocabulary', 'vocabulary_expected_rows'],
    ['lenses', 'lenses_expected_rows'],
    ['game_forms', 'game_forms_expected_rows'],
    ['realizations', 'realizations_expected_rows'],
    ['coverage', 'coverage_expected_rows'],
] as const

export interface SoccerModuleIntegrityResult {
    valid: boolean
    errors: string[]
}

/** The five data sheets, with the exact sheet name the projection expects to find. */
const DECLARED_SHEETS = [
    ['vocabulary', 'Vocabulary'],
    ['lenses', 'Lenses'],
    ['game_forms', 'Game Forms'],
    ['realizations', 'Realizations'],
    ['coverage', 'Coverage'],
] as const

/**
 * Metadata shape check — the guard against a round-tripped workbook.
 *
 * The workbook is edited on shared Drive. If it is converted to a Google Sheet and exported back,
 * typed values and sheet names can change without anyone touching a cell. The dangerous part is that
 * most of those changes do not error: a renamed sheet or a lost `*_header_row` key makes the
 * projection read the wrong row and produce an EMPTY sheet, which then looks like "the knowledge
 * hasn't been populated yet" rather than "the file arrived damaged".
 *
 * So this checks the declarations themselves rather than the data, and says *conversion* out loud in
 * the message — because the person reading the failure will otherwise go looking in the wrong place.
 */
export function validateModuleMetadataShape(data: SoccerModuleWorkbook = WB): string[] {
    const errors: string[] = []
    const meta = data.metadata
    const conversionHint = 'This usually means the workbook was converted to another format and exported back.'

    for (const [key, expectedSheetName] of DECLARED_SHEETS) {
        const nameKey = `${key}_sheet_name`
        const headerKey = `${key}_header_row`

        const declaredName = meta[nameKey]
        if (declaredName === undefined || declaredName === null) {
            errors.push(`Metadata is missing ${nameKey}. ${conversionHint}`)
        } else if (String(declaredName) !== expectedSheetName) {
            errors.push(
                `${nameKey}="${String(declaredName)}" but the projection expects the sheet named "${expectedSheetName}". ` +
                    `A renamed sheet makes every row read empty rather than failing. ${conversionHint}`
            )
        }

        // The projection DEFAULTS this to 2 when absent, so a lost key silently misreads the sheet
        // instead of erroring. Requiring it explicitly is what turns that into a named failure.
        const headerRow = meta[headerKey]
        if (headerRow === undefined || headerRow === null || !Number.isFinite(Number(headerRow))) {
            errors.push(
                `Metadata ${headerKey} is missing or non-numeric (got ${JSON.stringify(headerRow)}). ` +
                    `The projection would fall back to row 2 and could read the wrong header. ${conversionHint}`
            )
        }
    }

    // Version pins. A workbook that lost these is not identifiable, and a module whose provenance
    // cannot be established should not load quietly.
    for (const key of ['module_id', 'workbook_schema_version', 'runtime_interface_version']) {
        if (meta[key] === undefined || meta[key] === null || String(meta[key]).trim() === '') {
            errors.push(`Metadata is missing ${key}; the module cannot be identified or version-checked.`)
        }
    }

    return errors
}

/**
 * Load-time integrity gate, validated against the workbook's OWN declarations rather than against
 * numbers written here. The same principle as the six canonical libraries: if the workbook and the
 * projection disagree, that is a defined failure, never a silent one.
 */
export function validateSoccerModuleIntegrity(data: SoccerModuleWorkbook = WB): SoccerModuleIntegrityResult {
    // Shape first: if the declarations are damaged, the row counts below are meaningless — an empty
    // sheet would agree with an expected count of zero and the module would load looking fine.
    const errors: string[] = [...validateModuleMetadataShape(data)]
    const meta = data.metadata

    for (const [sheet, countKey] of COUNTED_SHEETS) {
        const declared = Number(meta[countKey])
        if (!Number.isFinite(declared)) {
            errors.push(`Metadata is missing ${countKey}; the loader cannot verify the ${sheet} sheet.`)
            continue
        }
        const actual = data[sheet].length
        if (declared !== actual) {
            errors.push(`${countKey}=${declared} but the projection holds ${actual} ${sheet} rows.`)
        }
    }

    if (String(meta['one_table_per_sheet'] ?? '').toUpperCase() !== 'TRUE') {
        errors.push('one_table_per_sheet must be TRUE — the projection assumes a single table per sheet.')
    }

    // Every populated row needs a stable identifier, or nothing downstream can reference it.
    const idColumns: Array<[keyof SoccerModuleWorkbook, string]> = [
        ['game_forms', 'game_form_id'],
        ['vocabulary', 'vocabulary_id'],
        ['lenses', 'lens_id'],
        ['realizations', 'realization_id'],
        ['coverage', 'coverage_id'],
    ]
    for (const [sheet, idColumn] of idColumns) {
        const seen = new Set<string>()
        for (const row of data[sheet] as SoccerModuleRow[]) {
            const id = row[idColumn]
            if (id === null || id === undefined || String(id).trim() === '') {
                errors.push(`A ${sheet} row is missing ${idColumn}.`)
                continue
            }
            const key = String(id)
            if (seen.has(key)) errors.push(`Duplicate ${idColumn} "${key}" in ${sheet}.`)
            seen.add(key)
        }
    }

    return { valid: errors.length === 0, errors }
}

/**
 * Universal identifiers the module cannot yet supply, reported rather than invented.
 *
 * Extraction surfaced these immediately: our game forms predate the canonical Game Archetype
 * Library and were never bridged to it, and routing goes through signal groups rather than GP-IDs.
 * Both need a decision from the knowledge side; guessing at them inside a loader would bury a
 * coaching judgement in code where nobody would ever find it.
 */
export function reportUnmappedUniversalIds(data: SoccerModuleWorkbook = WB): Record<string, number> {
    const missing = (rows: SoccerModuleRow[], column: string) =>
        rows.filter((r) => r[column] === null || r[column] === undefined || String(r[column]).trim() === '').length

    return {
        'game_forms.canonical_game_archetype_id': missing(data.game_forms, 'canonical_game_archetype_id'),
        'game_forms.primary_game_problem_ids': missing(data.game_forms, 'primary_game_problem_ids'),
    }
}

export const soccerModule = {
    metadata: WB.metadata,
    moduleId: String(WB.metadata['module_id'] ?? 'sport.soccer'),
    version: String(WB.metadata['workbook_schema_version'] ?? 'RC1-CANDIDATE-V3'),
    runtimeInterfaceVersion: String(WB.metadata['runtime_interface_version'] ?? ''),
    vocabulary: () => WB.vocabulary,
    lenses: () => WB.lenses,
    gameForms: () => WB.game_forms,
    realizations: () => WB.realizations,
    coverage: () => WB.coverage,
    gameForm: (id: string) => WB.game_forms.find((r) => String(r['game_form_id']) === id),
    realization: (id: string) => WB.realizations.find((r) => String(r['realization_id']) === id),
}
